### ISSUE TITLE
Sidhant Bhavnani

### ISSUE THREAD

**Issue by bhavnanisidhant** [open-source-society/computer-science#101]
- **Name**: Sidhant Bhavnani
- **GitHub**: [@bhavnanisidhant]()
- **Twitter**: [@bhavnanisidhant]()
- **Linkedin**: [link](https://www.linkedin.com/profile/preview?locale=en_US&trk=prof-0-sb-preview-primary-button)
- **Website**: [sidhant.me]()

## Completed Courses

**Compter Science**

Course|Files
:--|:--:
Introduction to Computational Thinking and Data Science by Massachusetts Institute of Technology (MIT)| [Edx](https://s3.amazonaws.com/verify.edx.org/downloads/10eb23b4c21741d0804403bd113326b7/Certificate.pdf)
Introduction to Computer Science and Programming Using Python by Massachusetts Institute of Technology (MIT)| [Edx](https://s3.amazonaws.com/verify.edx.org/downloads/0ccc9adae577437ba05728f6d79a6f5d/Certificate.pdf)
Introduction to Java by Hong Kong University of Science and Technology (HKUST)| [Edx](https://s3.amazonaws.com/verify.edx.org/downloads/f18b950ddcfa48b69d9e7b303e371096/Certificate.pdf)
Introduction to Big Data with Apache Spark by University of California Berkeley (UCB)| [Edx](https://s3.amazonaws.com/verify.edx.org/downloads/6b9431e2cb6f4265afc85af6c3de90c7/Certificate.pdf)

**Comment by svenluijten** [comment]
Comment in [this](https://github.com/open-source-society/computer-science-and-engineering/issues/31) issue *(please, do not open a new one)*

^ From the readme. Post a new comment on that issue and you're done :smile:
