### ISSUE TITLE
Mathematics for Computer Science

### ISSUE THREAD

**Issue by missingdays** [open-source-society/computer-science#104]
So there is greate MIT course [Mathematics for Computer Science]( http://www.youtube.com/watch?v=L3LMbpZIKhQ&list=PL3o9D4Dl2FJ8zkoLxaO4aKlq2JsKsz365 )
It covers topics like proofs by contradiction and induction, graphs, number theory and many more.
I think it would be a nice place for people to start if they are interested in math.

**Comment by ericdouglas** [comment]
@missingdays thanks for the suggestion. We are discussing about it [here](https://groups.google.com/forum/#!topic/open-source-society-university/HQRkYkGwFZA) and [here](https://github.com/open-source-society/computer-science/issues/93), too.

**Comment by missingdays** [comment]
@ericdouglas MOOC style courses are better than just videos for sure!
May be non-MOOC ( just videos) can be marked as non-MOOC or optional.

**Comment by ericdouglas** [comment]
@missingdays yes! What I'm thinking is to use nonMOOC courses strictly when we do not have a MOOC option.

Do you think that this course have things that are not covered in the ones listed here?

**Comment by maicoqb** [comment]
Maybe we can mark some courses as `optional`.
This is important, because some courses are not directly related with CS grade.

**Comment by missingdays** [comment]
@ericdouglas unfortunately I haven't completed any math courses listed here yet, so I can't be sure. But this MIT course covers basics of Math and it's approaches, rather than some specific topic like Linear Algebra or Game Theory. 
I guess it would be a good candidate for ```optional``` course as one of the starting points of learning Math.

**Comment by ericdouglas** [comment]
@maicoqb @missingdays it sounds good!

Maybe we can have something like this:

Courses|Required
:--|:--:
[Introduction to Computer Science](https://www.edx.org/course/introduction-computer-science-harvardx-cs50x#!)| `true`
[Introduction to Computer Science and Programming Using Python](https://www.edx.org/course/introduction-computer-science-mitx-6-00-1x-5#!)| `false`
[Introduction to Computational Thinking and Data Science](https://www.edx.org/course/introduction-computational-thinking-data-mitx-6-00-2x-2#!)| `true`

What do you think?

**Comment by missingdays** [comment]
@ericdouglas yeah, looks awesome!

**Comment by ericdouglas** [comment]
@missingdays :hand:

**Comment by maicoqb** [comment]
@ericdouglas That's it.

**Comment by ericdouglas** [comment]
@missingdays @maicoqb sorry for that, but a Required column will lead us to add a ton of courses here, and this will be a terrible experience for the students.

I'm working hard to complete our curriculum ASAP. I'll add the missing courses,  and sort those courses in the best way possible.

Give to me one day and I'll return with an awesome curriculum for us :wink:

**Comment by ericdouglas** [comment]
ps: @missingdays I think that we don't have a MOOC Discrete Math course, so I'll add your suggestion to our curriculum.

Thanks for pointing that out!

**Comment by maicoqb** [comment]
We can have also off-topic course category.

## Off-Topic Courses

**Machine Learning**

Courses|Required
:--|:--:
[Practical Machine Learning](https://www.coursera.org/course/predmachlearn)|```false```
[Neural Networks for Machine Learning](https://www.coursera.org/course/neuralnets)|```false```

The [Machine Learning](https://github.com/open-source-society/computer-science#machine-learning) course, stay where it is, but the others more deepest, will be moved to another category.
