### ISSUE TITLE
Google Groups vs Forum Solutions

### ISSUE THREAD

**Issue by brandonskerritt51** [open-source-society/computer-science#112]
As per discussion in Gitter
some people don't have a Google Account and want a prettier forum solution, one that isn't so outdated
A structure like
Main form for the OSS and sub forms for every course would be helpful aswell

**Comment by JohnnyBDude** [comment]
+1 i would love something other than google groups. Can any of you think of a solution?

**Comment by brandonskerritt51** [comment]
There's an online solution here http://www.forumotion.com/
But it may require a log in (unless you can somehow integrate this with Github?)
Heres an example of a forumotion page
http://www.avacweb.com/

**Comment by lisandro586** [comment]
What about a sub-reddit?

**Comment by brandonskerritt51** [comment]
You have the upvoting system which is bad imo, its good publicity for us though, and you would end up with people commenting on threads about courses
like thread
Welcome to computer science
then comments under it
I dislike that, as the entire course takes place over a year
unless we create regular threads?

**Comment by odiefrom** [comment]
Dropping in my two copper, http://discourse.org is a pretty awesome, free, open source forum software.  It shows both what is new across the entire forums, but then has Categories which is pretty much Boards/Sub-boards (as Categories can have children Categories).  http://try.discourse.com has a live board online to view how it works, and if you jump into their FAQ they have links to all kinds of boards being used by real groups.  Oh, and it supports GitHub login natively, so that save people from having to make a new account.

**Comment by ericdouglas** [comment]
Google groups :-1: 
Discourse :+1: 
Subreddit :+1: 

ps: with discourse, we need to have our own server to install it

**Comment by odiefrom** [comment]
@ericdouglas Discourse could probably be launched on a GitHub Page (ie., http://open-source-society.github.io).  Don't know for certain if GitHub Pages supports everything for Discourse, but hey, it's an avenue to investigate for the hosting of *any* forum/BBS

**Comment by ericdouglas** [comment]
@odiefrom look [here](http://blog.discourse.org/2014/04/install-discourse-in-under-30-minutes/)

**Comment by odiefrom** [comment]
I'd recommend DigitalOcean: I actually use the $5 tier "droplet" (instance) to run the VOIP server where I work.  The issue though is the obvious: it costs money someone has to put up.

**Comment by JohnnyBDude** [comment]
I think the DigitalOcean droplet would be nice (or any other VPS, but i have good experience with DO too). I could be useful in many other ways than just for hosting a forum. Maybe we could raise the money somehow? though I dont have much experience with that.

**Comment by bestknighter** [comment]
I think that both Discourse and a Subreddit are good ideas. But by now, using Discourse would be better. For the Subreddit we'll need a better planning of how it would work, the rules, etc. Maybe when the Open Source Society has another courses as well.

**Comment by JohnnyBDude** [comment]
Hah, dicourse gives you 10$ for DigitalOcean(which should cover a month of running). Installing that should be pretty easy as well http://blog.discourse.org/2014/04/install-discourse-in-under-30-minutes/

**Comment by dishark** [comment]
I could easy implement Discourse (i got reasonable knowledge in infrastucture and linux systems + @JohnnyBDude just mentioned a awesome article). I would need help to maintain though. Shall we setup a team to make this happen?

**Comment by ericdouglas** [comment]
With Discourse, we'll need a mail server too, because we're growing quickly, and SendGrid free account (12k emails/month) won't be sufficient.

@dishark I'm in!

**Comment by bestknighter** [comment]
Wow, is it me or this is starting to look like a 21st century university? This is so awesome!

At some point, this will be a huge thing in a way that will be hard to keep it running at no cost. How do big open-source projects/companies maintain themselves? We should research about this topic to keep these extra resources running.

**Comment by odiefrom** [comment]
If you're setting up a DO box, it's going to want/need it's own configuration for sendmail probably, to notify and such.  It would make sense throw an IMAP/POP3 with SMTP server on the DO as well.

You'd also need to figure out domain names.  http://dot.tk will grant a domain name for 1 year, with the extension .tk.  .org/.edu would be *very* difficult to obtain, or at least costly.

**Comment by ericdouglas** [comment]
@bestknighter I'm thinking this too!

@odiefrom yes, we need a domain, but this will be the cheapest thing. We only need to choose a good name :)

**Comment by QuincyLarson** [comment]
We blogged about the pros and cons of each for Free Code Camp here: http://blog.freecodecamp.com/2015_03_01_archive.html

**Comment by QuincyLarson** [comment]
One thing to point out about Discourse is we ran a medium sized AWS instance, and it was really slow. I think you'd need a large one, which is like $50 - $60/month.

**Comment by QuincyLarson** [comment]
Given that a lot of attention this project has received has come from Reddit, I'd suggest going with a subreddit.

**Comment by thebergamo** [comment]
I can support an digital ocean host for the project =D

**Comment by brandonskerritt51** [comment]
Digital ocean / discourse is the way to go in my option, a sub reddit would also be handy but I feel like we need a proper forum :)

**Comment by Ebisu77** [comment]
Why not all of them? We can have subreddit, we can have Google groups for those with Google account and once this project is ready for next step we can have own domain and migrate things there. On Github will stay only coding work and repos of students, web page will be place for official announcements, profiles of students, honor code, tips, faq, and of course some official forum which we definitely need, and subreddit will live its own live as always. We should see current ways of communication as temporary and only provisional status. I think we all have a feeling by now that this project might grow to be much bigger as was planned.

**Comment by ericdouglas** [comment]
@QuincyLarson thank you for your protips! I've to admit that I'm more inclined to start with a subreddit.

@Ebisu77 I agree with you in all your considerations.

Link to our [here](https://www.reddit.com/r/opensourcesociety/). Let's try this first, it's better than google groups for sure.

**Comment by dishark** [comment]
I did implement Discourse on Digital Ocean's $5 droplet -> [Link for test container](http://45.55.95.208/). It gives me tons of insufficient memory warnings, even with me following all theirs steps for get it running in such environment.

Also i had some trouble with SendGrid that didn't provisioned my account.

I thought about __Amazon's EC2__, but the cost will grow as we scale. Sounds good at first, but i think we are big already. So it can be a real disaster. We'll need to follow the open/free way.

**Comment by ericdouglas** [comment]
Hey, @dishark thank you for test it!

Let's use reddit by now, and after we can see if we need a better solution.

**Comment by dishark** [comment]
@ericdouglas my pleasure. Yeah reddit seems to fit for now. 

I never used it though, if anyone else needs a [guide](http://mashable.com/2012/06/06/reddit-for-beginners/#1fB4rSj94iqB).

**Comment by ericdouglas** [comment]
Closing here. We now have a /r/opensourcesociety channel :smile:
