### ISSUE TITLE
Signup

### ISSUE THREAD

**Issue by bprewit** [open-source-society/computer-science#114]
- **Name**: Bruce Prewit
- **GitHub**: [@bprewit]()
- **Linkedin**: [https://www.linkedin.com/pub/bruce-prewit/5/7a0/939]()

## Completed Courses

**Name of the Section**

Course|Files
:--|:--:
Course Name| [link]()

**Comment by sarath49** [comment]
Hi, Close this issue and open it as comment in #109 
Thanks
