### ISSUE TITLE
Questionable course order

### ISSUE THREAD

**Issue by enlait** [open-source-society/computer-science#119]
Section about programming paradigms lists Principles of Reactive Programming (RP) before Functional Programming Principles in Scala (FP in Scala); however FP in Scala is actually a prerequisite for RP (optional if you already know functional programming and Scala) since RP course is entirely in Scala.

This is explicitly said on RP course page, in Recommended Background section.

**Comment by ericdouglas** [comment]
@enlait many thanks for your advice! This will be fixed in the next release of our curriculum (today). :smile:
