### ISSUE TITLE
Learning how to learn

### ISSUE THREAD

**Issue by mseyne** [open-source-society/computer-science#120]
Hi, before to start the introduction to computer science, I would recommend to take a course in learning to learn : 
[Like this one](https://www.coursera.org/learn/learning-how-to-learn)
I feel it is a great introduction to the full adventure of learning the full cursus.

[Here a Ted video](http://www.scotthyoung.com/blog/myprojects/mit-challenge-2/) which can be an inspiration and help motivate people about their own capacity to learn by themselves:

Maybe you have others ?

**Comment by dvalpx** [comment]
Thanks for this :+1:

**Comment by ericdouglas** [comment]
@mseyne this is a great tip.

What do you think about add a section before "Curriculum" called **Preparation & Motivation**? So we can add those links.

**Comment by mseyne** [comment]
That sound a good idea, it can be a preparation for people who are intimidated to start and want to learn about their capacity to succeed to learn.
Also, peoples who are used to the classic education to accomplish tasks for someone else can have no idea about how to study by themselves and find motivation to do so.
I am doing the coursera mooc before the introductions about learning to learn, I find it very interesting so far.

**Comment by ericdouglas** [comment]
@mseyne awesome! I'll add those recommendations right now!

Thanks for pointing that out!
