### ISSUE TITLE
Open Study

### ISSUE THREAD

**Issue by mseyne** [open-source-society/computer-science#121]
Hi fellow learners, I have not been deep in it, I used it a bit with the [mechanical mooc](http://mechanicalmooc.org/) from de P2PUniversity.

But I heard it is a great tool for community learning, and I believe it could be interesting to have a tool like this (complementary to gitter and the subreddit ?).

http://openstudy.com/

**Comment by ericdouglas** [comment]
@mseyne I think that we already have sufficient channels for now...

Open Study looks like "too much information" to me.

Thank you for the suggestion!
