### ISSUE TITLE
OOS|CS

### ISSUE THREAD

**Issue by manjillama** [open-source-society/computer-science#127]
- **Name**: Manjil Tamang
- **GitHub**: [@manjillama]()
- **Twitter**: [@lamamanjil]()
- **Linkedin**: [None]()
- **Website**: [None]()

## Completed Courses

**Name of the Section**

Course|Files
:--|:--:
Course Name| [link]()

**Comment by 15100096** [comment]
- **Name**: Sohaib Elahi
- **GitHub**: [@15100096]()
- **Linkedin**: [https://www.linkedin.com/]()

## Completed Courses
Course|Files
:--|:--:
Course Name| [link]()

**Comment by ericdouglas** [comment]
@manjillama @15100096 

please, add your profile in the [issue](https://github.com/open-source-society/computer-science/issues) `#109`.

Thanks! :smile:
