### ISSUE TITLE
oss/cs

### ISSUE THREAD

**Issue by manjillama** [open-source-society/computer-science#129]
- **Name**: Manjil Tamang
- **GitHub**: [@manjillama]()
- **Twitter**: [@lamamanjil]()
- **Linkedin**: [NA]()
- **Website**: [NA]()

## Completed Courses

**Name of the Section**

Course|Files
:--|:--:
Course Name| [link]()

**Comment by sarath49** [comment]
Please close this issue and add your student profile at #109 
Thanks :)

**Comment by ericdouglas** [comment]
@sarath49 thanks :wink:
