### ISSUE TITLE
Contributing to the OSS university app

### ISSUE THREAD

**Issue by SoullessWaffle** [open-source-society/computer-science#131]
## Students
Students, please note that it is **not necessary** to become an OSS member if you just want to apply for the curriculum. You can apply for the curriculum by clicking [this link][apply] and following the instructions on the page.

## Pull requests
We welcome pull requests! :smile: 
If you want to contribute your code for the development of the OSS university app, you can open pull requests to the `develop` branches of the [front-end][front-end] or [back-end][back-end].
Please don't open pull requests to the `master` branches.

## Membership
That said, if you want to become a regular contributor to the project and a member of the Open Source Society, here are the steps you need to take:

1. Please fill out [this form here][form]
2. Within 48 hours we will send you a Slack invite so you can introduce yourself and come chat with us
3. If all goes well, we will send you an invite to the OSS organization on GitHub

[apply]: https://github.com/open-source-society/computer-science/issues/109
[front-end]: https://github.com/open-source-society/ossu-ui/tree/develop
[back-end]: https://github.com/open-source-society/ossu-api/tree/develop
[form]: https://soullesswaffle.typeform.com/to/xuTU4O

**Comment by ericdouglas** [comment]
Will be added to the CONTRIBUTING file :smile: 

Thank you @SoullessWaffle :pray:
