### ISSUE TITLE
Computer Science

### ISSUE THREAD

**Issue by Umair37** [open-source-society/computer-science#132]
**Name**: UMAIR TARIQ
- **GitHub**: [@UMAIR37]()
- **Twitter**: [@tariqumair5]()
- **Website**: [compissue.blogspot.com]()

Completed Courses

**Name of the Section**

Course|Files
:--|:--:
Course Name| [link]()

**Comment by ericdouglas** [comment]
@Umair37 

please, add your profile on issue `#109` named `Students Profile #2`, [here](https://github.com/open-source-society/computer-science/issues)

Thanks! :smile:

**Comment by Umair37** [comment]
Thanks :)
