### ISSUE TITLE
Umair Tariq

### ISSUE THREAD

**Issue by Umair37** [open-source-society/computer-science#134]
**Name**: UMAIR TARIQ
- **GitHub**: @UMAIR37
- **Twitter**: @tariqumair5
- **Website**: compissue.blogspot.com

## Completed Courses

**Name of the Section**

Course|Files
:--|:--:
Course Name| [link]()

**Comment by sarath49** [comment]
Please open your student profile @ #109 
Thanks :)

**Comment by ericdouglas** [comment]
@sarath49 thank you!
