### ISSUE TITLE
Open Source Development

### ISSUE THREAD

**Issue by oharrison** [open-source-society/computer-science#140]
Could we possibly find a MOOC that teaches the FOSS ecosystem and development workflow?

**Comment by ericdouglas** [comment]
Hey, @oharrison this would be great, but I'm afraid that we do not have such course right now.

I know one, but is focused for JavaScript Developers.

[This one](https://egghead.io/series/how-to-write-an-open-source-javascript-library).

I also wrote an article based on that course [here](http://ericdouglas.github.io/2015/09/27/checklist-for-your-new-open-source-javascript-project/).
