### ISSUE TITLE
Enroll

### ISSUE THREAD

**Issue by zonayedpca** [open-source-society/computer-science#141]
- **Name**: ZONAYED AHMED
- **GitHub**: [@zonayedpca]()
- **Twitter**: [@zonayedpca]()

## Completed Courses

**Name of the Section**

Course|Files
:--|:--:
Course Name| [-]()

**Comment by ericdouglas** [comment]
@zonayedpca 

please, add your profile on issue `#109` named `Students Profile #2`, [here](https://github.com/open-source-society/computer-science/issues)

Thanks! :smile:
