### ISSUE TITLE
Joined

### ISSUE THREAD

**Issue by GavinDmello** [open-source-society/computer-science#151]
Name: Gavin D'mello
GitHub:GavinDmello
Twitter:@bat_coder
Linkedin: https://goo.gl/8C6hkv

## Completed Courses
**Name of the Section**

Course|Files
:--|:--:
Course Name| [link]()

**Comment by mseyne** [comment]
Please, use this [issue](https://github.com/open-source-society/computer-science/issues/145)
Thank you :smile:
