### ISSUE TITLE
[README.md] "Citation needed"

### ISSUE THREAD

**Issue by mbrookes** [open-source-society/computer-science#152]
"By making a [public commitment](http://renewablewealth.com/articles/the-power-of-a-public-commitment/), we have a greater chance of successfully graduating"

The linked article has a single data point, aka ["anecdata"](https://en.wiktionary.org/wiki/anecdata).

[Counterpoint](http://www.spring.org.uk/2011/10/why-you-should-keep-your-goals-secret.php) backed by [research](http://www.ncbi.nlm.nih.gov/pubmed/19389130).

**Comment by ericdouglas** [comment]
@mbrookes thank you for pointing that out!

[Removed](https://github.com/open-source-society/computer-science/blob/master/CHANGELOG.md#124-2015-10-14).
