### ISSUE TITLE
Students Profiles #3

### ISSUE THREAD

**Issue by MuteInspiration** [open-source-society/computer-science#154]
- **Name**: Jun Min Kim
- **GitHub**: [@MuteInspiration](https://github.com/MuteInspiration)
- **Twitter**: [@j08031](https://twitter.com/j08031)
- **Linkedin**: [link](http://www.linkedin.com/in/mutega)

## Completed Courses

**Name of the Section**

Course|Files
:--|:--:
Course Name| [link]()

**Comment by mseyne** [comment]
Please, could you use this [issue](https://github.com/open-source-society/computer-science/issues/145)
Thank you.
