### ISSUE TITLE
profile

### ISSUE THREAD

**Issue by wlsk5882** [open-source-society/computer-science#157]
- **Name**: Jina Lee
- **GitHub**: @wlsk5882
- **Twitter**: @wlsk5882

## Completed Courses

**Name of the Section**

Course|Files
:--|:--:
Course Name| [link]()

**Comment by jbhum** [comment]
Please, could you use this [link](https://github.com/open-source-society/computer-science/issues/145) in order to sign up!
Thank you.

**Comment by maicoqb** [comment]
@wlsk5882 please, move your comment to #145 and close this issue. :+1: :smiley:

**Comment by ericdouglas** [comment]
@jbhum @maicoqb ty!
