### ISSUE TITLE
Wow, great!  Let's dive in!

### ISSUE THREAD

**Issue by dennisnam** [open-source-society/computer-science#159]
- **Name**: Dennis Nam
- **GitHub**: [@dennisnam]()
- **Twitter**: [@dennisnam]()
- **Linkedin**: [kr.linkedin.com/in/dennisnam]()
- **Website**: [dennisnam.com]()

## Completed Courses

**Name of the Section**

Course|Files
:--|:--:
Course Name| [link]()

**Comment by jbhum** [comment]
Please, could you use this [link](https://github.com/open-source-society/computer-science/issues/145) in order to sign up!
Thank you.
