### ISSUE TITLE
Kathy Park 

### ISSUE THREAD

**Issue by parksoku** [open-source-society/computer-science#161]
- **Name**: Kathy Park
- **GitHub**: [@parksoku]()

## Completed Courses

**Name of the Section**

Course|Files
:--|:--:
Course Name| [link]()

**Comment by jbhum** [comment]
Please, could you use this [link](https://github.com/open-source-society/computer-science/issues/145) in order to sign up!
Thank you.

**Comment by parksoku** [comment]
I used that link to update my profile but it keeps posting here.
Is there any solution?

**Comment by TerenceCooper** [comment]
1. Click on the "issues" button.
![1](https://cloud.githubusercontent.com/assets/15084574/10474260/3ea5c432-7267-11e5-8e1c-c41a945915fd.jpg)
2. Click on the "#3" link.
![2](https://cloud.githubusercontent.com/assets/15084574/10474281/6cd06330-7267-11e5-9533-0ba486e7dae8.jpg)
3.Scroll down to the page bottom and leave your profile comments there. And we are done!  :)
![3](https://cloud.githubusercontent.com/assets/15084574/10474284/856b2b14-7267-11e5-9042-9f2a74630e1c.jpg)

**Comment by ericdouglas** [comment]
@TerenceCooper thanks you! :smile:
