### ISSUE TITLE
KangByungWook

### ISSUE THREAD

**Issue by KangByungWook** [open-source-society/computer-science#165]
- **Name**: Kang Byung Wook
- **GitHub**: [@kangbyungwook]()
- **Twitter**: [@your_username]()
- **Linkedin**: [link]()
- **Website**: [yourblog.com]()

## Completed Courses

**Name of the Section**

Course|Files
:--|:--:
Course Name| [link]()

**Comment by Semigradsky** [comment]
> Comment in [this](https://github.com/open-source-society/computer-science-and-engineering/issues/145) issue (please, do not open a new one)

**Comment by maicoqb** [comment]
@KangByungWook please, move your comment to #145 and close this issue. :+1: :smiley:

**Comment by ericdouglas** [comment]
@Semigradsky @maicoqb ty!
