### ISSUE TITLE
Profile

### ISSUE THREAD

**Issue by charliePNU** [open-source-society/computer-science#166]
- **Name**: Sungchul Shin
- **GitHub**: [@charliePNU]()
- **Twitter**: [@scshin71]()
- **Linkedin**: [Sungchul Shin]()
- **Website**: [Building]()

## Completed Courses

**Name of the Section**

Course|Files
:--|:--:
n/a| [n/a]()

**Comment by maicoqb** [comment]
@charliePNU please, move your comment to #145 and remove this issue. :+1: :smiley:

**Comment by ericdouglas** [comment]
@maicoqb ty!
