### ISSUE TITLE
enrollment

### ISSUE THREAD

**Issue by archdo0909** [open-source-society/computer-science#167]
- **Name**: Doyeon.K
- **GitHub**: [@archdo0909]()
- **Twitter**: [@]()
- **Linkedin**: []()
- **Website**: []()

## Completed Courses

**Name of the Section**

Course|Files
:--|:--:
Course Name| [link]()

**Comment by jbhum** [comment]
Please open issue [#145](https://github.com/open-source-society/computer-science/issues/145) and place your enrollment at the end of that file.
