### ISSUE TITLE
Can't Make Some Courses

### ISSUE THREAD

**Issue by Swadish** [open-source-society/computer-science#169]
I'm trying to do the 
Software Architecture > Web Application Architectures (https://www.coursera.org/course/webapplications)
course on Coursera, but the only option is to get advised when they'll have sessions of the course.
Is there a way to get the course any time I want or I'll have to wait until they do a session of the course?

Thanks!

**Comment by mseyne** [comment]
Yes, we need to wait until the day it open. Then enroll even if we don't plan to do it at this time, to keep the materials open when the course session is finished.

**Comment by ericdouglas** [comment]
That's it :smile: 

@mseyne ty!
