### ISSUE TITLE
Functional programming alternative course?

### ISSUE THREAD

**Issue by a2wd** [open-source-society/computer-science#174]
Would you consider adding the [edX/DelftU Functional Programming Introduction](https://www.edx.org/course/introduction-functional-programming-delftx-fp101x-0) as an alternative to the suggested course in Scala, it is in Haskell which is a pure functional language. Any thoughts?

**Comment by ericdouglas** [comment]
@a2wd this course was in an older version of the curriculum. I removed it because the another one have its continuation course.

Personally  I'd love to take this course too, and indeed I'll, but I'm afraid to put these two courses here in our curriculum as an "obligatory" course.

We can see what others students have to say. 

My vote is to include this course in our curriculum as well. This can be the first one in the Programming Paradigms section.

**Comment by prashcr** [comment]
The Scala course seems to be much more popular and well-reviewed. The Prof invented Scala and wrote javac (the compiler).

The Haskell course seems to be newer and while it has decent ratings, I see a lot of repeated criticism about its teaching methods, mostly along the lines of "the lectures don't give you enough background to complete the tasks".

Pure vs impure shouldn't be a sole criteria I think. In my opinion, pure functional languages come off as more "experimental" and it should be left as an elective. Scala on the other hand, is the most popular FP language used in the industry, and presents tremendous opportunity.

It's definitely true that Scala tolerates bad FP habits, but I guess you could interpret it as a "choice" between sticking to purely FP or imperative.

Disclaimer: I've done neither of the two languages, but I studied ML as an elective at school.

**Comment by prashcr** [comment]
The fact that the reactive programming class builds on top of the scala course is another important consideration, we can't simply swap out the scala course if we're keeping the reactive course.

Interesting fact: I noticed that Erik Meijer, the instructor of the Haskell course, is also an instructor for the reactive course.

**Comment by ericdouglas** [comment]
> "The Scala course seems to be much more popular and well-reviewed. The Prof invented Scala and wrote javac (the compiler).
>
> The Haskell course seems to be newer and while it has decent ratings, I see a lot of repeated criticism about its teaching methods, mostly along the lines of "the lectures don't give you enough background to complete the tasks"."

For those reasons, I decided to remove the Haskell course. Let's keep this course out of our curriculum, it'll be better.

@prashcr thank you for remember me about those things :smile:
