### ISSUE TITLE
Hello World

### ISSUE THREAD

**Issue by fengshuinality** [open-source-society/computer-science#178]
- **Name**: Nick Nicholas
- **GitHub**: [@your_username]()
- **Twitter**: [@nichbarry]()
- **Linkedin**: [link]()
- **Website**: [yourblog.com]()

## Completed Courses

**Name of the Section**

Course|Files
:--|:--:
Course Name| [link]()

**Comment by mseyne** [comment]
Please consider using this [issue](https://github.com/open-source-society/computer-science/issues/145).
