### ISSUE TITLE
Add "Louv1.1x Paradigms of Computer Programming" course

### ISSUE THREAD

**Issue by hails** [open-source-society/computer-science#181]
Could you add the Peter Van Roy's course [Louv1.1x Paradigms of Computer Programming](https://courses.edx.org/courses/course-v1:LouvainX+Louv1.1x+3T2015/info) to the `Programming Paradigms` section?

**Comment by ericdouglas** [comment]
@hails thank you for your suggestion, but we already have 3 courses in this section. I'm afraid that this could become a little overwhelming.

With those 3 courses, we'll have a solid foundation about programming paradigms.
