### ISSUE TITLE
Student Profile

### ISSUE THREAD

**Issue by aLordCo** [open-source-society/computer-science#183]
- **Name**: Alexander Ortiz Arévalo
- **GitHub**: [@aLord]()
- **Twitter**: [@aLord_Co]()

## Completed Courses

**Introduction to Computer Science**

Course|Files
:--|:--:
Introduction to Computer Science | []()
Introduction to Computer Science and Programming Using Python | []()
Introduction to Computational Thinking and Data Science | []()
From Nand to Tetris | []()

**Comment by ericdouglas** [comment]
@aLordCo 

please, add your profile on issue `#180` named `Students Profile #4`, [here](https://github.com/open-source-society/computer-science/issues)

Thanks! :smile:
