### ISSUE TITLE
Student profile limit issue threads and top level message structure

### ISSUE THREAD

**Issue by shaun10** [open-source-society/computer-science#187]
I noticed the first message in some of the student threads differs from issue to issue. Should it be uniform? There is a typo in the newest student profile issue #4 with the top level comment also.

Just speculating is there another way to list students without it being listed in issues that start to slow down as comments increase.

**Comment by ericdouglas** [comment]
@shaun10 yes, we're working on an app to give students ability to enroll and track their progress.

Look [here](https://github.com/open-source-society).

:smile:
