### ISSUE TITLE
johnjoseph1990

### ISSUE THREAD

**Issue by johnjoseph1990** [open-source-society/computer-science#192]
- **Name**: Minyoung.Choi
- **GitHub**: johnjoseph1990
- **Twitter**: [@your_username]()
- **Linkedin**: [link]()
- **Website**: minslab.me

**Comment by ericdouglas** [comment]
@johnjoseph1990 

please, add your profile on issue `#180` named `Students Profile #4`, [here](https://github.com/open-source-society/computer-science/issues)

Thanks! :smile:
