### ISSUE TITLE
My Profile

### ISSUE THREAD

**Issue by xinluqishi** [open-source-society/computer-science#201]
- **Name**: xinluqishi
- **GitHub**: [@xinluqishi]()
- **Twitter**: [@xinluqishi]()
- **Linkedin**: [link]()
- **Website**: [http://www.cnblogs.com/xinluqishi/]()

## Completed Courses

**Name of the Section**

Course|Files
:--|:--:
Course Name| [link]()

**Comment by ericdouglas** [comment]
@xinluqishi 

please, add your profile on issue `#180` named `Students Profile #4`, [here](https://github.com/open-source-society/computer-science/issues)

Thanks! :smile:
