### ISSUE TITLE
Zachary Rosenbauer

### ISSUE THREAD

**Issue by zrosenbauer** [open-source-society/computer-science#205]
- **Name**: Zachary Rosenbauer
- **GitHub**: [@zrosenbauer](https://github.com/zrosenbauer)
- **Twitter**: [@zrosenbauer](https://twitter.com/zrosenbauer)
- **Linkedin**: [link](https://www.linkedin.com/in/zacrosenbauer)
- **Website**: [zacrosenbauer.com](http://www.zacrosenbauer.com)

## Completed Courses

**Name of the Section**

Course|Files
:--|:--:
Introduction to Computer Science| [link](https://www.edx.org/course/introduction-computer-science-harvardx-cs50x#!)

**Comment by ericdouglas** [comment]
@zrosenbauer please, add your profile on issue `#180` named `Students Profile #4`, [here](https://github.com/open-source-society/computer-science/issues)

Thanks! :smile:
