### ISSUE TITLE
CS Student

### ISSUE THREAD

**Issue by callousfury** [open-source-society/computer-science#210]
- **Name**: Andy Walsh
- **GitHub**: @callousfury
- **Twitter**: @callousfury
- **Linkedin**: https://www.linkedin.com/pub/andrew-walsh/4b/b79/aa4

**Comment by ericdouglas** [comment]
@callousfury 

Can you please add your profile on issue `#206` named `Students Profile #5`, [here](https://github.com/open-source-society/computer-science/issues) !?

Thanks! :smile:
