### ISSUE TITLE
Can I suggest one more awesome *Parallel Computing* course?

### ISSUE THREAD

**Issue by ydwu** [open-source-society/computer-science#214]
It's a Udacity interactive course **Intro to Parallel Programming**.
It covers the fundamental of GPGPU parallel computing and contains very useful examples and exercises. 

Here's the link:
https://www.udacity.com/course/viewer#!/c-cs344

**Comment by ericdouglas** [comment]
@ydwu 

this is an interesting course, for sure!

Let's see if there are more considerations from other students before we add or not this course into our curriculum.

:smile:

**Comment by mseyne** [comment]
@ericdouglas we can also do a file in help with all the course we find and class them, for those who want to custom more deeply the curriculum. I thought about this after the discover of @hangtwentyy course about machine learning. I had already this one : https://www.coursera.org/course/hetero. It will open in january. Udacity is always open.

**Comment by crmackay** [comment]
not sure if this makes sense with this course, but at some point more "in depth" courses might be better served on a "specialization" or "grad-level" list, which this OSS-CS list representing more of a undergrad CS sequence that  touches on every topic to some degree, but not into too much depth. Granted I am unable to judge what level makes sense. I just know as someone starting from course 1, if this CS list just keeps growing, then it begins to seem more and more unattainable. I understand lifelong learning is a goal, but achieving certain milestones is important to maintain momentum, so constantly moving the goal posts back is not ideal. I don't have a good solution to this, but there are other options to address this issue as well, like inserting certain miletones within the sequence that students achieve sequentially, etc.  

Another idea would for this particular situation would be to have list "alternatives courses" that satisfy the same requirement. For example, perhaps it could be recommended that you should to take one of the two parallel computing courses, and the decision to take coursera vs udacity is up to the student, course, availability, etc.

**Comment by ericdouglas** [comment]
@mseyne yeah we can/should do this. I just think that we can create another repository for such thing.

@crmackay you're totally right. I truly believe that we have a pretty solid/stable curriculum here, and I'm concerned about those things that you told.

Let's do a "win-win" solution here. We should add more courses, but in an optional list. :smile:
