### ISSUE TITLE
Student Profile

### ISSUE THREAD

**Issue by sundancekid1108** [open-source-society/computer-science#216]
- **Name**: woncheol yang
- **GitHub**: [@sundancekid1108]()
- **Twitter**: [@your_username]()
- **Linkedin**: [link]()
- **Website**: [yourblog.com]()

## Completed Courses

**Name of the Section**

Course|Files
:--|:--:
Course Name| [link]()

**Comment by sundancekid1108** [comment]
hello world

**Comment by ericdouglas** [comment]
@sundancekid1108 

Can you please add your profile on issue `#206` named `Students Profile #5`, [here](https://github.com/open-source-society/computer-science/issues) !?

Thanks! :smile:
