### ISSUE TITLE
hey i have suggestion.

### ISSUE THREAD

**Issue by ganganimaulik** [open-source-society/computer-science#217]
https://www.reddit.com/r/cs50/comments/1nx2au/life_after_cs50

see link, there are some links to other coerces... take any from it to make this perfect.

**Comment by ericdouglas** [comment]
@ganganimaulik thanks for the link! But we already have a bunch of courses here :smile: 

We'll create an `extra` folder to allow our students suggest additional resources.

**Comment by ganganimaulik** [comment]
all-right buddy :)
