### ISSUE TITLE
Michelle

### ISSUE THREAD

**Issue by michellesuchang** [open-source-society/computer-science#219]
- **Name**: Michelle 
- **GitHub**: [@michellesuchang](https://github.com/michellesuchang)

## Course in Progress

**Intro to Computer Science**

Course|Files
:--|:--:
Intro to Computer Science| [Harvard CS50](https://www.edx.org/course/introduction-computer-science-harvardx-cs50x)

**Comment by ericdouglas** [comment]
@michellesuchang 

Can you please add your profile on issue `#206` named `Students Profile #5`, [here](https://github.com/open-source-society/computer-science/issues) !?

Thanks! :smile:
