### ISSUE TITLE
 open-source-society/computer-science

### ISSUE THREAD

**Issue by Neoloss** [open-source-society/computer-science#224]
- **Name**: Aslan
- **GitHub**: [@Neoloss]()
- **Linkedin**: [https://www.linkedin.com/in/aslan-atarov-19a8b046]()

## Completed Courses

**Name of the Section**

Course|Files
:--|:--:
Course Name| [link]()

**Comment by ericdouglas** [comment]
@Neoloss 

Can you please add your profile on issue `#206` named `Students Profile #5`, [here](https://github.com/open-source-society/computer-science/issues) !?

Thanks! :smile:

**Comment by Neoloss** [comment]
Got confused a little bit, sorry ))

Thanks

**Comment by ericdouglas** [comment]
@Neoloss no problem! :+1:
