### ISSUE TITLE
enrolling in course

### ISSUE THREAD

**Issue by ubergeekgirl** [open-source-society/computer-science#225]
Jessica DeVita
@ubergeekgirl
@ubergeekgirl
https://www.linkedin.com/in/jessicadevita
theubergeekgirl.com

## Completed Courses

**Name of the Section**

Course|Files
:--|:--:
Course Name| [link]()

**Comment by miguel550** [comment]
"You are supposed to comment Issue 206 (scroll down the page to Student Profiles 5), not open a new one"
