### ISSUE TITLE
Remove mentions of udemy.com from README.md

### ISSUE THREAD

**Issue by pierrebeaucamp** [open-source-society/computer-science#226]
Hey,

I just wanted to get a discussion going regarding udemy.com. It's getting lots of bad press right now for selling pirated content. A good summary: [How Udemy Is Profiting From Piracy](https://medium.com/@robconery/how-udemy-is-profiting-from-piracy-5638b929ffca).

OSS links to no courses on Udemy, however it's featured in `README.md` as an educational platform.

What do you think?

**Comment by srs1978** [comment]
I think personally that it should go.

**Comment by schlomok** [comment]
Agreed. Additionally, one of the (perhaps unspoken) tenants of OSS is that everything seems to be freely available -- udemy.com is mostly not a free platform. I think this should be considered.

**Comment by ni8mr** [comment]
Some of the courses of Udemy are free which can be considered as enough reason to add them in the list. But if piracy is the concern, they should be removed.

**Comment by ericdouglas** [comment]
Done! :smile:

**Comment by 007lva** [comment]
:+1: :+1:
