### ISSUE TITLE
Reordering of Discrete Math

### ISSUE THREAD

**Issue by ghost** [open-source-society/computer-science#229]
[Discrete Math](http://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-042j-mathematics-for-computer-science-fall-2010/Syllabus/) requires Single Variable Calculus as a prerequisite. 

I'd suggest the Calculus courses should come before Discrete Math in the curriculum.

Calculus > Discrete Math > Algorithms

**Comment by Heasummn** [comment]
I agree. The Discrete Mathematics course touches on some math that many people using this, those who want to self teach and are not in any way professional on the subject, have never used, me included. The Calculus course, as well as some Khan Academy cleared that up, but following the exact structure of the courses becomes confusing.

**Comment by hugja** [comment]
I was thinking along the lines of Calculus, Discrete Math, then Algorithms in order.

**Comment by jaredStef** [comment]
+1

**Comment by ericdouglas** [comment]
This was discussed [here](https://github.com/open-source-society/computer-science/issues/139).
