### ISSUE TITLE
student

### ISSUE THREAD

**Issue by stephenleefoon** [open-source-society/computer-science#230]
- **Name**: Stephen Lee-Foon
- **GitHub**: [@stephenleefoon]()
- **Twitter**: 
- **Linkedin**: 
- **Website**: 

## Completed Courses

**Name of the Section**

Course|Files
:--|:--:
Course Name| [link]()

**Comment by miguel550** [comment]
"You are supposed to comment Issue 206 (scroll down the page to Student Profiles 5), not open a new one"
