### ISSUE TITLE
Please add Introduction to Programming in Java (MIT) to the curriculum

### ISSUE THREAD

**Issue by dswallow** [open-source-society/computer-science#242]
Hello,

I think this would be a nice addition to the curriculum:

### Programming Languages

Courses | Duration | Effort
:-- | :--: | :--:
[Introduction to Programming in Java (MIT)](http://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-092-introduction-to-programming-in-java-january-iap-2010/index.htm)| 4 weeks | 4-6 hours/week

**Comment by jerobarraco** [comment]
i dont think that a special language should be mandatory

**Comment by dswallow** [comment]
It doesn't have to be mandatory. It is a good course that helps people who specifically want to learn about Java, like myself

**Comment by mottosso** [comment]
I'm with @jerobarraco.

This list of for mandatory subjects. It clearly states that once you're finished with *all* of these, you are encouraged to pursue further, more in-depth, topics on your own.

**Comment by jerobarraco** [comment]
Yes, a bloated curricula es not useful to anyone.
If you see [here](https://github.com/open-source-society/computer-science/issues/31#issuecomment-146058063), i'm doing a course that is not on the curricula, so as @mottosso, i'm more than ok with pursuing personal specialization.
I think a way to address this would be to have a *separated list* of "recommended" extra courses.

**Comment by dswallow** [comment]
Ok, so it states "After finishing the courses above, start your specializations". Since no one has gotten this far yet, I think there is some room for flexibility. 'Introduction to Programming in Java' would be too easy for someone who has completed all the courses listed. However, it is good course that is also recommended by Google in their [Guide to Technical Development] (https://www.google.com/about/careers/students/guide-to-technical-development.html) and it is also on MIT's list of [Most Visited Courses] (http://ocw.mit.edu/courses/most-visited-courses/) (Two really helpful links, btw!) so it would be a shame for an OSS student to miss the class. My suggestion would be to have three categories 'core', 'specialised' and 'electives' to account for this flexibility.

**Comment by mottosso** [comment]
I don't know. I think that if anything kills this project, it would be too many individuals thinking their interests supersedes the interest of the whole.

If this course is to be added, something has to be removed. The author of the current list obviously put a lot of effort in making a broad range of topics that doesn't overlap (at least I'd like to think so). So if you can narrow down which course(s) you think this can replace, then I wouldn't have a problem with it. Otherwise, this course will go from taking 3 years to 6 years to 12 years, in no time.

**Comment by stabuev** [comment]
I think you can take you by yourself, and add to your profile as nonOSS course.

**Comment by jerobarraco** [comment]
+1 @mottosso and @stabuev 
i love @dswallow suggestion of having different "specializations" that are optional.
Ie, i like security, project management, psychology, games and python. 
there could be different optional specialization that you could *choose* to do if you want to pursue that path.
In Argentina (my country) "electives" have a special meaning, which says that you MUST do it too. which leads to what @mottosso  says. And i strongly think that the duration should be as short as possible. In my local community we had this discussion and think that the market needs basic trained ppl very quick. Most of them only need 1 to 2 years of training.

In _this particular_ case, java is not very different from other languages, in that it's the same paradigm, so it's not a core part of a system engineer knowledge (as not is python or ruby either). but can be learned very quickly once you know OOP. I'm not underestimating java, i work teaching it. But the same core ideas can be learned with a variety of courses. 
IMHO maybe is better to have a good, short course that teaches this core idea, then expand to an optional specialization with a quick and short course about a language of choice.
with the least overlapping of content as possible.

**Comment by ericdouglas** [comment]
Hey, guys!

We have [those files](https://github.com/open-source-society/computer-science/tree/master/extras) to accept suggestions from our students. Now we just need to state in our readme how to do this.

I'll do this ASAP.

Thank you for all of your suggestions in this thread!
