### ISSUE TITLE
Coursera courses limited archived availability

### ISSUE THREAD

**Issue by JPinlac** [open-source-society/computer-science#243]
From my understanding, Coursera courses are no longer indefinitely available to view in archives. This is variable according to the institution. For example an institution may only make the archives available for a few months, a year, etc. 

This poses a problem with some of the coursera courses such as Princeton's Algorithms 1 and 2. Perhaps add alternative's to these courses?

**Comment by davidschwalbe** [comment]
Here is an alternative
https://www.coursera.org/course/algo
There is also a part II

**Comment by dswallow** [comment]
Here is an alternative
https://www.coursera.org/course/algo
There is also a part II

**Comment by JPinlac** [comment]
That works perfectly, thanks.

**Comment by dswallow** [comment]
Let me know how you go. I just completed the first programming exercise and would be willing to help out if you run into any problems.
