### ISSUE TITLE
Is there a way to directly contact other OSS students?

### ISSUE THREAD

**Issue by dswallow** [open-source-society/computer-science#245]
Hello,
I would like to collaborate with people who are taking the same classes as I am. I see GitHub removed the private messaging feature, which would have been perfect.

**Comment by miguel550** [comment]
The [Community Section](https://github.com/open-source-society/computer-science#community) in the Readme file shows how you can interact with others students. :+1:

**Comment by ericdouglas** [comment]
Thank you again @miguel550 !
