### ISSUE TITLE
Open source? Problem sharing files.

### ISSUE THREAD

**Issue by jerobarraco** [open-source-society/computer-science#247]
Ok, so i like open source, and in this curricula it's encouraged to share the material generated for the each course.
I really like that, and i try to share as much as possible of what i generate.
Though while doing CS50 i find this restriction on the submitted work:

        Not allowed to:
        Providing or making available solutions to problem sets to individuals who might take this course in the future.

which basically forbids me to share anything i do for the course. 
I could wait to finish the course to share what i do, but it says "in the future" so that means nopes.

What do you think about that?
![serverconf1](https://cloud.githubusercontent.com/assets/3729895/12213315/bcfca3d8-b654-11e5-99ed-e45b16b2bf68.png)

**Comment by dswallow** [comment]
I have also thought about this. I think for CS50 it would be unreasonable to give someone a link directly to your solved problem sets but for Scratch and the final project this would be ok. What do you think?

**Comment by jerobarraco** [comment]
@dswallow  thanks for commenting.
well i just recently (2 Secs ago) submitted the 1st set. and i noticed there's a quiz at the end. obviously i'm not going to publish my answers for that. 
but also i noticed that the scratch site makes your stuff public, and you need to enter the url when submitting, so i think maybe its not a crime to upload the scratch solution to my public repository. 
https://scratch.mit.edu/projects/93513819 < this is my submission, if you can see it then it's public.

**Comment by dswallow** [comment]
Yeah its public :). Mine is [here] (https://scratch.mit.edu/projects/86548316/). I will be starting pset5 next week!

**Comment by mottosso** [comment]
I've also noticed this! At least the final project should be freely shareable, I'm working on mine at the moment. :)

- https://github.com/mottosso/blur

**Comment by jerobarraco** [comment]
Hey congratulations to both! I'm going slow because of work and other courses.
I should talk to the teachers, about this, if any of you do it please let me know.

**Comment by miguel550** [comment]
As OSSU is Project Based I think what you need to share is the files of the project or projects you create using the knowledge you got from the course and not the solutions of the problems that are in the course.

**Comment by ericdouglas** [comment]
@miguel550 exactly!

We treat about this topic [here](https://github.com/open-source-society/computer-science#content-policy) :smile:
