### ISSUE TITLE
cloud computing

### ISSUE THREAD

**Issue by muteness** [open-source-society/computer-science#252]
The course under cloud computing seems to be a business oriented one.

I would suggest the [Cloud Computing Concepts](https://www.coursera.org/course/cloudcomputing) on Coursera.

**Comment by ericdouglas** [comment]
This is an interesting course, we certainly need to add this specialization course in our [extras section](https://github.com/open-source-society/computer-science/tree/master/extras).

The current course about CC has [good reviews](https://www.coursetalk.com/providers/edx/courses/cloudintrox-introduction-to-cloud-computing#reviews), and this is one of the most important requisites for our curriculum.
