### ISSUE TITLE
OSSU 2.0

### ISSUE THREAD

**Issue by ericdouglas** [open-source-society/computer-science#271]
Now that we have an [extras section](https://github.com/open-source-society/computer-science/tree/master/extras), we are able to let our curriculum a little more concise.

With this in mind, some courses will be moved to the extras section, keeping our program **really feasible**.

The main reasons for those changes are:

- keep our curriculum as concise as possible
- valorize the courses that pay more attention to teaching concepts
- Leave the in-depth courses in the extras section as specialization of the respective topics

### Courses to be (re)moved

- **Introduction to Computer Science**: 
	- Introduction to Computer Science
	- Introduction to Computational Thinking and Data Science
- **Algorithms**
	- Analysis of Algorithms
- **Programming Paradigms**
	- Principles of Reactive Programming
- **Math (Calculus)**
	- Multivariable Calculus
- **Software Architecture**: 
	- Web Application Architectures
- **Software Engineering**: 
	- Agile Development Using Ruby on Rails - Basics
	- Agile Development Using Ruby on Rails - Advanced
	- Startup Engineering
- **Computer Architecture**: 
	- The Hardware/Software Interface
- **Operating Systems**: 
	- Operating System Engineering
- **Computer Networks**: 
	- Introduction to Computer Networking
- **Cryptography**: 
	- Applied Cryptography

**Comment by TehLeviter** [comment]
Since I already started CS50 (on week 2 atm), should I just finish it or just go with the new version?

**Comment by ericdouglas** [comment]
@TehLeviter CS50 and MIT6.00 are equivalents. You can choose to complete one or another (or both).

**Comment by AhmedKamal20** [comment]
@ericdouglas  Are they equivalent to Stanford's CS101 ?

**Comment by ericdouglas** [comment]
@AhmedKamal20 yes, MIT 6.00 is a little more concise, but the purpose of both courses is to be an introduction to Computer Science.

**Comment by mahmoudelhofy** [comment]
what about udacity computer science course 
is it equilivant to those

**Comment by ericdouglas** [comment]
@mahmoudelhofy yes, they are all equivalent. :+1:

**Comment by rodrigobaron** [comment]
Why **Introduction to Computational Thinking and Data Science** goto extra section? 

> This course is the first of a two-course sequence: Introduction to Computer Science and Programming Using Python, and Introduction to Computational Thinking and Data Science. Together, they are designed to help people with no prior exposure to computer science or programming learn to think computationally and write programs to tackle useful problems.

now seems that something is missing...

**Comment by ericdouglas** [comment]
@rodrigobaron this course is more like a complement. The necessary introductory concepts about Computer Science are presented in the first course, as you can see [here](https://courses.edx.org/asset-v1:MITx+6.00.1x_8+1T2016+type@asset+block/6001x_syllabus.pdf).

Other subjects and concepts will be covered by the subsequent courses in our curriculum.

Thank you for exposing your doubt. Perhaps more students were with similar concerns. :smile:

**Comment by rodrigobaron** [comment]
@ericdouglas all right, nice. So maybe we can add some extra/optional section in curriculum something like that
![scheen](https://cloud.githubusercontent.com/assets/790725/14389584/a5bde066-fd89-11e5-8452-387cf3cf68d4.PNG)
([or using panel tabs](http://bootsnipp.com/snippets/featured/panels-with-nav-tabs))
what you think?

**Comment by ericdouglas** [comment]
@rodrigobaron yes, for sure! This is an important feature that we must have.

In fact, we discussed a little about such feature [here](https://github.com/open-source-society/ossu-client/issues/29) :smile: 

I liked your suggestion to add an `[Extra]` tag!

Fell free to send more suggestions for us here or in the other issue related to that specific feature.

Thank you for your collaboration! :pray:

**Comment by rodrigobaron** [comment]
yep! I will contribute :smile:
