### ISSUE TITLE
Intro

### ISSUE THREAD

**Issue by oillataguerre** [open-source-society/computer-science#273]
- Name: Ryan Oillataguerre

- GitHub: oillataguerre

- Twitter: rmoillataguerre

- LinkedIn: https://www.linkedin.com/in/ryan-oillataguerre-42924110b?trk=hp-identity-name

**Comment by ericdouglas** [comment]
@oillataguerre please add your profile in the issue `Students Profiles #6`.

Thank you! :smile:
