### ISSUE TITLE
andrea'Buffa

### ISSUE THREAD

**Issue by abuffa8** [open-source-society/computer-science#275]
- **Name**: Andrea 'Buffa
- **GitHub**:(@abuffa8)
- **Twitter**: [@your_username]()
- **Linkedin**:(Andrea Buffa)
- **Website**: [yourblog.com]()

## Completed Courses

**Name of the Section**

Course|Files
:--|:--:
Course Name| [link]()

**Comment by ericdouglas** [comment]
@abuffa8 please add your profile on the issue `Students Profile #6`.

Thank you! :smile:
