### ISSUE TITLE
Introduction Post

### ISSUE THREAD

**Issue by cbunch81** [open-source-society/computer-science#279]
- **Name**: Curtis Bunch
- **GitHub**: [@cbunch81]()
- **Twitter**: [@curtisbunch]()
- **Linkedin**: [https://www.linkedin.com/in/curtisbunch]()
- **Website**: []()

## Completed Courses

**Name of the Section**

Course|Files
:--|:--:
Course Name| [link]()

**Comment by ericdouglas** [comment]
@cbunch81 please, add your info in the issue `Students Profile #6`.

Thank you! :smile:
