### ISSUE TITLE
Discrete optimization

### ISSUE THREAD

**Issue by QtRoS** [open-source-society/computer-science#280]
Hi guys, you should add this course:
https://www.coursera.org/course/optimization

**Comment by ni8mr** [comment]
Good one.

**Comment by QtRoS** [comment]
One of the best courses I ever passed (you can see full list in my record). Awesome instructor, interesting staff and submissions!

**Comment by ericdouglas** [comment]
@QtRoS can you send a pull request to add this course to our extras section? More about it [here](https://github.com/open-source-society/computer-science#how-to-collaborate).

Thank you for your collaboration :smile:

**Comment by ericdouglas** [comment]
#281
