### ISSUE TITLE
Impact of Coursera closing its old platform

### ISSUE THREAD

**Issue by Drmikej** [open-source-society/computer-science#282]
Will there be any impact on the curriculum of Coursera transitioning completely to its new platform and shutting down the original (in June as I understand it)
In particular I am trying to find out is Algorithms I and Algorithms II are in their final presentations or if they will be moved.  and have ha on a Discussion thread i
Are any other courses "at risk".
Disclosure:
I'm editor of I Programmer where backing in October we wrote an article: OSS University - A Free Computer Science Degree Curriculum [](http://www.i-programmer.info/news/150-training-a-education/9070-oss-university-a-free-computer-science-degree-curriculum.html)

I've had a very slow and so far uninformative response from Coursera's PR and discovered from the Algorithm's II discussion thread that students may not be aware of this issue at all.

Please could you contact Sue Gee (writer of the above article) if you have information/reactions/comments to incorporate in a new article sue-dot-gee-at-i-hyphen-programmer-dot-info.
Thanks

**Comment by ericdouglas** [comment]
@Drmikej I'm not aware of this change in its platform, but if this situation affects our curriculum, we'll fix it using alternatives for those affected courses.

Thank you by informing us about this topic.

:smile:
