### ISSUE TITLE
Problem of checking pset and quiz answer for edX archived course

### ISSUE THREAD

**Issue by li-xinyang** [open-source-society/computer-science#284]
I am currently doing my first course [MITx: 6.00.1x](https://courses.edx.org/courses/course-v1:MITx+6.00.1x_8+1T2016/info). This is an archived course on **edX**. 

I can use in lecture quiz to check my answer but for **Problem Set** (No answer for some problem set) and [**Quiz**](https://courses.edx.org/courses/course-v1:MITx+6.00.1x_8+1T2016/courseware/19136f9d4de045fdab0ce099230f5385/af94467328b74ed38f0e901460166d70/) there is no way to check my answer (For Quiz there is  no answer provided).

For problem set, I have to check the answer by providing my own testing function, but I am afraid that the test case I provided may not comprehensive enough to cover all cases.

Is there a way to get quiz and problem set answer?

**Comment by MirzaI** [comment]
No, pretty sure this is an intentional policy by Edx to prevent cheating. Only way to get all quizzes and problems is to enroll next time course runs.

**Comment by li-xinyang** [comment]
Thanks for your response. I will close this issue.
