### ISSUE TITLE
Enter on OSS

### ISSUE THREAD

**Issue by gollodev** [open-source-society/computer-science#291]
- **Name**: Jose Lopez
- **GitHub**: [@gollodev]()
- **Twitter**: [@gollodev]()
- **Linkedin**: [https://www.linkedin.com/in/joselopezcv/]()
- **Website**: [joselopezweb.com]()

## Completed Courses

**Name of the Section**

Course|Files
:--|:--:
Course Name| [link]()

**Comment by ericdouglas** [comment]
@gollodev please, add your profile in the issue `Students Profile #6`. 

Thank you! :smile:
