### ISSUE TITLE
New

### ISSUE THREAD

**Issue by Itagiba** [open-source-society/computer-science#295]
- **Name**: YOUR NAME
- **GitHub**: [@your_username]()
- **Twitter**: [@your_username]()
- **Linkedin**: [link]()
- **Website**: [yourblog.com]()

## Completed Courses

**Name of the Section**

Course|Files
:--|:--:
Course Name| [link]()

**Comment by AhmedKamal20** [comment]
@ericdouglas 
I think you need to rewrite the part that say "please don't make a new one"
make it bigger , a whole lot bigger

**Comment by ericdouglas** [comment]
@AhmedKamal20 yes :sweat_smile: but we'll use another way soon, that is our [web app](https://github.com/open-source-society/ossu-client). We just need to add a little more information before change the way of enrolling in OSSU.

**Comment by ericdouglas** [comment]
@Itagiba please add your profile to the issue Students Profiles #6. Thank you! :smile:
