### ISSUE TITLE
New Student 

### ISSUE THREAD

**Issue by ahmedfl** [open-source-society/computer-science#296]
- **Name**: Ahmed Nagi
- **GitHub**: [@ahmedfl]()
- **Facebook**: [@ahmednagi1997]()
- **Linkedin**: [https://www.linkedin.com/in/ahmed-nagi-a01825110]()

## Completed Courses

**Name of the Section**

Course|Files
:--|:--:
Course Name| [link]()

**Comment by ericdouglas** [comment]
@ahmedfl please add your profile in the issue Students Profiles #6. Thank you! :smile:
