### ISSUE TITLE
Tamer Hakoum

### ISSUE THREAD

**Issue by Hakoum** [open-source-society/computer-science#297]
**Name**: Tamer Hakoum
- **GitHub**: [@hakoum]()
- **Twitter**: n/a
- **Linkedin**: n/a
- **Website**:n/a

## Completed Courses

**Mobile Computing with App Inventor - CS Principles**

Course|Files
:--|:--:
Course Name| [https://www.edx.org/course/mobile-computing-app-inventor-cs-trinityx-t002x]()

**Comment by li-xinyang** [comment]
@ericdouglas This is annoying for those who are watching this repo. 

It is also hard for the student to update their information in this way. Will you consider to use an alternative method to register new student OR remove **Becoming an OSS Student** section in README?

**Comment by ericdouglas** [comment]
@Hakoum please, look into our [new way to enroll in OSSU](https://github.com/open-source-society/computer-science#becoming-an-oss-student)! :smile: :tada: 

@li-xinyang you're totally right. Apologies for this annoying situation :sweat:, but it's fixed now! Thank you for your feedback.
