### ISSUE TITLE
Student at OSS

### ISSUE THREAD

**Issue by OkPro-OmarElKhatib** [open-source-society/computer-science#298]
- **Name**: Omar ElKhatib
- **GitHub**: [@OkPro-OmarElKhatib]()
- **Website**: [n/a]()

**Comment by ericdouglas** [comment]
@OkPro-OmarElKhatib please, look into our [new way to enroll in OSSU](https://github.com/open-source-society/computer-science#becoming-an-oss-student)! :smile: :tada:
