### ISSUE TITLE
The Hardware/Software Interface Course

### ISSUE THREAD

**Issue by Ayman97** [open-source-society/computer-science#303]
Nice Course for how computers work.
https://class.coursera.org/hwswinterface-002/

**Comment by ericdouglas** [comment]
@Ayman97 could you create a pull request and add this course in our [extras](https://github.com/open-source-society/computer-science/tree/master/extras) section?

**Comment by mkghosh** [comment]
@Ayman97 You should close this issue as the course has been added in the extras section.
