### ISSUE TITLE
OSSU 3.0

### ISSUE THREAD

**Issue by ericdouglas** [open-source-society/computer-science#316]
A lot of students are having problems to enroll in the course "Introduction to Computer Science and Programming Using Python". For that reason, it is appropiate to return CS50 to our main curriculum, because at least by now, it is a Self-Paced course.

The course "From Nand to Tetris" will also be moved to our `extras` section, because the following message is showed in the assignment topics:

> "Purchase course to unlock this item."

To preserve the free experience of our program, we will also move this course to the extras section, to avoid any confusion for our students.

- [x] Move CS50 to main curriculum
- [x] Move MIT 6.00 to extras
- [x] Move From Nand to Tetris to extras
- [x] Bump the curriculum version
- [x] Add the modifications to CHANGELOG file

**Comment by shailalias** [comment]
I appreciate the effort to keep the main curriculum completely free. With that, will courses like "From Nand to Tetris" be replaced with free alternatives?

**Comment by ericdouglas** [comment]
@shailalias From Nand to Tetris is indeed free, just the assignment section that has some restrictions, but you are still able to see what have to be done.

The course will be moved more to prevent some bad experience that our students may have because of this message, which is a bit intimidating.

**Comment by ericdouglas** [comment]
A little more about the modifications in the **Introduction to Computer Science** section:

I really apologize for this annoying situation.

But there were good reasons for doing so:

1. Initially, MIT 6.00 (Introduction to Computer Science and Programming Using Python) was self-paced. Now, it isn't, and the next session starts in June.

2. Initially, From Nand to Tetris didn't have the "pay to unlock" kind of thing, what is something not that good, especially for an introductory course.

These were the reasons for those modifications.

I hope that you understand, and don't forget that MIT 6.00 and CS50 are equivalents, as well as other courses that we have in the extras section.

If you're doing the MIT 6.00 course right now, you could continue this without a problem.

Sorry again :pray:

**Comment by xangria** [comment]
I really appreciate the clarification!
