### ISSUE TITLE
CS50 not updated on your web app

### ISSUE THREAD

**Issue by Tmahesh07** [open-source-society/computer-science#318]
Hi 

I'm new to the OSS university and I'm glad that i found this amazing resource, however i have found one issue on your web app by registering it shows the old course not the new CS50 

I'm starting  CS50 today not sure how i will track my progress?

Regards
Mahesh

**Comment by ericdouglas** [comment]
Hey @Tmahesh07 , thank you for pointing this out!

This is a known issue, and you can follow its progress [here](https://github.com/open-source-society/ossu-client/issues/42).

You can open issues related with the web app in [this](https://github.com/open-source-society/ossu-client) repository :smile:
