### ISSUE TITLE
"Effective Thinking Through Mathematics"

### ISSUE THREAD

**Issue by jcirizar** [open-source-society/computer-science#320]
The course "Effective Thinking Through Mathematics" on EDX, has the videos privates.

**Comment by rouzazari** [comment]
I'm experiencing the same problem, as are others on the edX course's discussion boards. 

I sent a message to edX's support today, and I'm waiting to hear back. Alternatively there may be a replacement course.

Please let me know if you find a solution.

**Comment by rouzazari** [comment]
This has been **resolved for me** about an hour after taking the following actions:
1) Linked my Google account under Account Settings (under the assumption this could have some affect on YouTube access)
2) Using the Help>Report a Problem tab on the left-hand side to note that UT.9.01x videos were not showing and were labeled as Private.

**Comment by ericdouglas** [comment]
@jcirizar are you still having trouble viewing the videos? Here everything is ok.
