### ISSUE TITLE
Linking OSSU Progress to Github Repository

### ISSUE THREAD

**Issue by KalikaKay** [open-source-society/computer-science#325]
Crazy question; I'm sure has an easy answer.

How do I link my Github repositories to the OSSU website such that I can review my progress and finished courses?

**Comment by ericdouglas** [comment]
@KalikaKay 

1. Go to [OSSU app](https://ossu.firebaseapp.com/#/)
1. Login with your GitHub (GH) account
1. In "My Progress" tab, click on the pencil icon for the respective course that you want to update the status and/or add the URL to your GH repository
1. Paste the URL of your GH repository into the input saying `Provide a link to repo`
1. Click in the check ✔ icon to save your information

That's it! :smile:

**Comment by KalikaKay** [comment]
I don't have a pencil.

I've an option to search. Results come back empty:

![ossumyprogress](https://cloud.githubusercontent.com/assets/19244222/15488981/3d20b482-2121-11e6-80e1-a30a0052ea2c.png)

**Comment by SergeyKhval** [comment]
Hi, @KalikaKay 
Do I understand you correctly, that after loging in your course list is empty?
If so, I suppose somethnig went wrong during profile creation. I can reset your account and you will need to log in again. This will most likely solve your issue. Does this option suit you?

**Comment by KalikaKay** [comment]
Hi @SergeyKhval,

Absolutely!

**Comment by SergeyKhval** [comment]
@KalikaKay try to log in again. Please let me know if the problem remains.
Have a nice day.

**Comment by KalikaKay** [comment]
Thank you @SergeyKhval and @ericdouglas! 

The course list is displaying.
I have successfully added my github repository link to the list and marked a course as in progress.

:+1:

**Comment by codxse** [comment]
I have same issue with @KalikaKay, I have no pencil icon on my progress tab. Would you reset my account too please?

**Comment by sarahsatzger** [comment]
@codxse I had the same issue just now, but hit the "reset progress" button on the left side of the page, and after resetting all the courses showed up. If you don't have any progress to risk losing, may be worth a try!
