### ISSUE TITLE
Current course does not appear in web app.

### ISSUE THREAD

**Issue by bandarr** [open-source-society/computer-science#326]
I'm currently enrolled in CS50x, but it does not show up in the web app:

![image](https://cloud.githubusercontent.com/assets/18521413/15509293/fc5dee6c-21a0-11e6-89c7-c1ff58153920.png)

Thanks.

**Comment by SergeyKhval** [comment]
Did you join OSSU before curriculum upgrade to 3.0 #316 ?

According to this issue open-source-society/ossu-client#42 this course will be added only for newly registered users.

**Comment by bandarr** [comment]
Yes.  Sounds like I would need to "de-register" and re-register.

**Comment by johnaoss** [comment]
Is there any way to upgrade existing user's accounts or does everyone have to be manually moved.

**Comment by SergeyKhval** [comment]
@johnaoss currently there is no way to automatically update user profiles. this is one of features that is work in progress.

**Comment by bandarr** [comment]
@SergeyKhval please tell me exactly what I need to do to get on the 3.0 curriculum.

**Comment by bandarr** [comment]
@SergeyKhval Can I get some help on this one?

**Comment by bandarr** [comment]
@SergeyKhval @johnaoss @erictherobot @jonathantorres @nickcannariato  Any help?

**Comment by codxse** [comment]
@SergeyKhval I am new member, how do I edit my progress?? I have same issue with #325

**Comment by ericdouglas** [comment]
I'll close this issue because it's related with our web-app.

Feel free to reopen that issue [here](https://github.com/open-source-society/ossu-client/issues).
