### ISSUE TITLE
Make an official badge for OSSU repositories

### ISSUE THREAD

**Issue by iamale** [open-source-society/computer-science#329]
It would be rather great great to link back from OSSU repositories (the ones that students set up) back to the app (or this repo?) itself, so those who don't yet know about it would be able to just click and see. The best way to do so is probably with a badge or something; maybe it сould be like the Awesome badge [![Awesome](https://cdn.rawgit.com/sindresorhus/awesome/d7305f38d29fed78fa85652e3a63e154dd8e8829/media/badge.svg)](https://github.com/sindresorhus/awesome), but also should fit in with generic shields.io-style ones (in case one would like to use it in a “real project” too). What do you think?

**Comment by ericdouglas** [comment]
@iamale that's a great idea!

**Comment by ericdouglas** [comment]
@iamale added! Thank you so much for your idea :smile: :pray:
