### ISSUE TITLE
Coursera goes close all courses on old platform ((

### ISSUE THREAD

**Issue by ol3gart** [open-source-society/computer-science#330]
Hello!
Coursera goes close up all courses on old platform.
https://reachtarunhere.github.io/2016/06/11/Golden-Age-of-MOOCs-is-over-and-why-I-hate-Coursera/
For now, we can download courses before 30, June. After this date the free downloading has been closed.
We have a plan to do with this issue?
coursera downloader:
https://github.com/coursera-dl/coursera-dl
https://news.ycombinator.com/item?id=11882735

**Comment by ericdouglas** [comment]
@ol3gart 

Well, this is a sad news.

Let's wait until they shut down the old platform and see how many courses of our curriculum will be really affected.

Our first 6 courses are from other course providers, so this will not affect that much instantly, IMO.

Thanks for pointing this out! :pray:
