### ISSUE TITLE
Coursera's closed courses from 30th of June

### ISSUE THREAD

**Issue by scelio** [open-source-society/computer-science#331]
30 June will close hundreds of courses on coursera.org including courses from OSS path: Automata, Computer Architecture, Computer Networks, Coding the Matrix: Linear Algebra through Computer Science Applications, Compilers. Need to find a replacement.

**Comment by li-xinyang** [comment]
You can download them before they remove all of them. Checkout `coursera-dl` on GitHub (Link below). 

https://github.com/coursera-dl/coursera-dl

**Comment by scelio** [comment]
I know, and downloaded two courses — Automata and Natural Language Processing. But now coursera.org removed the ability to download courses with this tool, or they periodicaly "are down for maintenance" :-).  And what about prospective students who will join the OSS after the 30th of June?

**Comment by mauriciv** [comment]
They will also remove Algorithms Part I & II, and Heterogeneous Parallel Programming

**Comment by karanshh1** [comment]
Most of the courses that are being removed are up for download via torrents.By searching for [coursera] on kat.cr I see that most of the removed courses (Algorithms Part I & II, and Heterogeneous Parallel Programming) can be found along with assignments. user eru_melkor has some stuff on kat.cr as well.

**Comment by dswallow** [comment]
According to http://online.princeton.edu/courses Algorithms, Part I and II are Upcoming but... all courses are "temporarily unavailable" at the moment.
It looks like Coursera is going to keep [Algorithms: Design and Analysis, Part 1](https://www.coursera.org/learn/algorithm-design-analysis/) and Part II is also in their catalog. I haven't looked up the other courses but it would surprise me if the universities completely remove their online content. Standford, Princeton and MIT have their own platforms so I would I start looking there. Some Professors also have there online content advertised on their homepages.

**Comment by yakschuss** [comment]
Is there a step-by-step instruction to getting the courses that will be discarded? (besides the script, which courses will be discarded, which ones are open for enrollment, and potential replacements for those specific ones.)

**Comment by ericdouglas** [comment]
#339

**Comment by rdotdk** [comment]
FYI, archive.org has preserved coursera courses.
https://archive.org/details/archiveteam_coursera
