### ISSUE TITLE
"Automata" is not available anymore

### ISSUE THREAD

**Issue by marceloboeira** [open-source-society/computer-science#337]
Coursera redirects to: https://www.coursera.org/browse?source=deprecated_spark_cdp
With the following message: "We're sorry, that course is not available at this time. Feel free to browse our extensive catalog."

**Comment by marceloboeira** [comment]
The same happens with "Computer Networks"

**Comment by benbrandt** [comment]
@marceloboeira I believe this is because of Coursera's platform change (see issues #330 and #331)

**Comment by marceloboeira** [comment]
@benbrandt yeap, I will close this one and wait for #331 👍 Thanks!

**Comment by ericdouglas** [comment]
@marceloboeira thank you for pointing this out, I'll fix the curriculum ASAP :smile:

Some courses that I saw are still there on the new platform, so I need to understand what changed with them all.

**Comment by fjcero** [comment]
In June 30 all deprecated courses were deleted. Most of them are available
to download through torrents or similar. I think Class Central have some
related links.
