### ISSUE TITLE
Courses to be replaced

### ISSUE THREAD

**Issue by ericdouglas** [open-source-society/computer-science#339]
Due to the new Coursera platform, those following courses are no more available, and will be replaced.

- **Theory**
  - [x] Automata - *new*: [Intro to Theoretical Computer Science](https://br.udacity.com/course/intro-to-theoretical-computer-science--cs313/)

- **Computer Networks**
  - [x] [Computer Networks](https://lagunita.stanford.edu/courses/Engineering/Networking-SP/SelfPaced/about)

- **Math (Linear Algebra)**
  - [x] Coding the Matrix: Linear Algebra through Computer Science Applications - *new*: [Linear Algebra - Foundations to Frontiers](https://www.edx.org/course/linear-algebra-foundations-frontiers-utaustinx-ut-5-04x#ct-read-review-widget)

- **Compilers**
  - [x] [Compilers](https://lagunita.stanford.edu/courses/Engineering/Compilers/Fall2014/about)

- **Parallel Computing**
  - [x] Heterogeneous Parallel Programming - *new*: [Parallel Computer Architecture and Programming](http://15418.courses.cs.cmu.edu/spring2016/home)

- **Natural Language Processing**
  - [x] Natural Language Processing - *new*: [Natural Language Processing](https://www.coursera.org/learn/nlp)

**Comment by MirzaI** [comment]
I believe 2of those courses can be found on stanfords own mooc platform in self-paced form. Google stanford + compilers/computer networks

**Comment by ericdouglas** [comment]
@MirzaI I'm updating the courses today and yes, I found those 2 courses on Stanford Online, thank you so much for your tip! :pray:
