### ISSUE TITLE
Profile lists all courses as completed.

### ISSUE THREAD

**Issue by samfrances** [open-source-society/computer-science#349]
My profile on the firebase apps lists all courses under "Finished courses". This doesn't seem likely to be the desired behaviour - I haven't recorded any progress at all yet.

My profile: https://ossu.firebaseapp.com/#/profile/github:2003369

**Comment by ericdouglas** [comment]
@samfrances could you open that issue on our [web-app repository](https://github.com/open-source-society/ossu-client/issues)?

**Comment by samfrances** [comment]
Will do.
