### ISSUE TITLE
Natural Language Processing course

### ISSUE THREAD

**Issue by andrecsq** [open-source-society/computer-science#351]
"Thanks so much for your interest in Natural Language Processing! Alas, we're writing to tell you that the Natural Language Processing class was listed by mistake, and we weren't even aware it was listed; we are not offering NLP this year. We apologize for the mistake, and we do hope to get back to this course someday, but we have no plans to do so anytime soon. We regret that we won't be able to work with you, but we warmly wish you all the best in your future in Natural Language Processing."

This was the message I received today on my e-mail from Coursera. Since the course will not be offered anytime soon, should probably change it.

**Comment by alexuv** [comment]
Hi andrecsq, I created a [pull request](https://github.com/open-source-society/computer-science/pull/352) addressing your issue.

**Comment by ericdouglas** [comment]
@andrecsq yes, I'll change it now :smile:
