### ISSUE TITLE
How I can get access to Effective Thinking Through Mathematics

### ISSUE THREAD

**Issue by batizhevsky** [open-source-society/computer-science#353]
Hello, anyone has archive of videos/lectures of the course?
Registration to a previews version is closed and the new [starts only in October .](https://www.edx.org/course/effective-thinking-through-mathematics-utaustinx-ut-9-01x-0)

**Comment by wavded** [comment]
I just enrolled and am waiting till it starts, not sure if there is any other way to get in.

**Comment by andrecsq** [comment]
I enrolled and am waiting. There is another course called "Mathematical Thinking" that I think you can take, its prob similar.

**Comment by corza334** [comment]
I think this is the 2014 one
https://courses.edx.org/courses/UTAustinX/UT.9.01x/1T2014/info

**Comment by ericdouglas** [comment]
It's open now! :tada:

**Comment by batizhevsky** [comment]
Some ideas to backup courses? I think it will be great

**Comment by ericdouglas** [comment]
@batizhevsky you just need to enroll in the course, so after you always be able to see the archives of such course.
