### ISSUE TITLE
Calculus comes first before Linear Algebra?

### ISSUE THREAD

**Issue by lixsee** [open-source-society/computer-science#355]
Hi.  I am starting out the course.  My minor gripe though was calculus 1 and 2 came first before linear algebra.  I thought it should be the other way around?  Please verify.  Thank you.

**Comment by P1xt** [comment]
Calculus actually does come before linear algebra in a standard curriculum.

I do question why calculus comes after mathematics for computer science though as it's listed as a direct prerequisite if you look at http://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-042j-mathematics-for-computer-science-fall-2010/Syllabus/

**Comment by gillchristian** [comment]
I took both clasess when I was doing the Bioengineering degree, Calculus was before Linear Algebra.

**Comment by ericdouglas** [comment]
Thank you guys for your collaboration. 

I'll move the Calculus section and it will come before Discrete Math.

So we will have the following sections:
```
Calculus
Discrete Math
Algorithms
...
```
