### ISSUE TITLE
slow internet

### ISSUE THREAD

**Issue by nandu42** [open-source-society/computer-science#356]
for students who have slow  internet please provide course materials downlode option in .zip file lot's of student don't have fast internet  access. we need all course material offline please help us .(uplode in google drive ) edx dl not working

**Comment by andrecsq** [comment]
you can download stuff from edx courses from youtube. all videos from edx (all ive watched so far) are uploaded to youtube.

**Comment by nandu42** [comment]
i tried with edx dl but its not working ..how can i downloade 17 hours of small segmented videos

**Comment by andrecsq** [comment]
sadly you cant. you would have to go one by one in the youtube link and download each one of them with some kind of youtube downloader

**Comment by maitreyav** [comment]
@nandu42 What about  Torrent links of the course?

**Comment by dhruvramdev** [comment]
Learn Programming . U will be alble to download All videos with single script

**Comment by nandu42** [comment]
edx dl have  trouble with very long paths file name is too long..

**Comment by ericdouglas** [comment]
@nandu42 in Coursera you can right click the video and save.

In edX you can go to YouTube and use a program to download the video, for example, [this one](http://www.clipconverter.cc/).

We can't do much about this topic.
