### ISSUE TITLE
 there are too much blank links!  why you still put them there?

### ISSUE THREAD

**Issue by xgqfrms-GitHub** [open-source-society/computer-science#359]
> introduction to Computer Science
> 
> Name	Author(s)
> Structure and Interpretation of Computer Programs	Hal Abelson, Jerry Sussman, Julie Sussman
> Introduction to Computing: Explorations in Language, Logic, and Machines	David Evans
> Math (Mathematical Thinking)
> 
> Program Design
> 
> Math (Discrete Math)
> 
> Algorithms
> 
> Programming Paradigms
> 
> Software Testing
> 
> Math (Calculus)
> 
> Name	Author(s)
> Calculus Made Easy	Silvanus P. Thompson
> Software Architecture
> 
> Theory
> 
> Software Engineering
> 
> Math (Probability)
> 
> Name	Author(s)
> Grinstead and Snell’s Introduction to Probability	Charles M. Grinstead, J. Laurie Snell
> Computer Architecture
> 
> Operating Systems
> 
> Computer Networks
> 
> Databases
> 
> Cloud Computing
> 
> Math (Linear Algebra)
> 
> Cryptography
> 
> Security
> 
> Compilers
> 
> Name	Author(s)
> Compiler Construction	Niklaus Wirth
> Parallel Computing
> 
> UX Design
> 
> Computer Graphics
> 
> Artificial Intelligence
> 
> Machine Learning
> 
> Name	Author(s)
> Deep Learning	Ian Goodfellow, Yoshua Bengio and Aaron Courville
> Natural Language Processing
> 
> Big Data
> 
> Data Mining
> 
> Internet of Things

@erictherobot 
@mkghosh

**Comment by benbrandt** [comment]
I believe it's so there's a structure for people to know where to place new books/course so that they match the categories of the main courses.

**Comment by xgqfrms-GitHub** [comment]
all right!
have fun!

**Comment by xgqfrms-GitHub** [comment]
**gameover!**
