### ISSUE TITLE
OSSU webapp not saving changes

### ISSUE THREAD

**Issue by awahhab** [open-source-society/computer-science#362]
every time I logout from webapp at https://ossu.firebaseapp.com/ and login again, I find my progress is removed. just like I reset my profile.

**Comment by astrotee** [comment]
same problem here

**Comment by ericdouglas** [comment]
To save your progress in the web app you should do:

1. Go to [My Progress](https://ossu.firebaseapp.com/#/account) page.
1. Click the pencil icon.
1. Paste a link to your repository and/or change the Status of the course to `Not Started`, `In Progress` or `Finished`.
1. Click the check icon.

And that's it. A notification will appear in the top right of your screen saying "Course saved".

Are you @awahhab @astrotee doing this?

If you still have problems, please open an issue [here](https://github.com/open-source-society/ossu-client) that is our web app repository.

Thanks! :smile:

**Comment by awahhab** [comment]
Thank you @ericdouglas 
I opened a new issue here https://github.com/open-source-society/ossu-client/issues/58
