### ISSUE TITLE
Some links need to be updated

### ISSUE THREAD

**Issue by andy5995** [open-source-society/computer-science#366]
On the [curriculum page](https://ossu.firebaseapp.com/#/curriculum), these links lead to the message "We're sorry, that course is not available at this time."

[Compilers](https://www.coursera.org/course/compilers)
[Computer Networks](https://www.coursera.org/course/comnetworks)

**Comment by ericdouglas** [comment]
@andy5995 many thanks! I'll open an issue in the [ossu-client](https://github.com/open-source-society/ossu-client) and close this one.
