### ISSUE TITLE
Validate classes taken in College

### ISSUE THREAD

**Issue by gillchristian** [open-source-society/computer-science#369]
Is it valid to list the classes that I've taken and passed in college as passed?

The courses are:

- Calculus One and Two
- Linear Algebra
- Object Oriented Programming in C++
- Discrete Math
- Computers Architecture _I might need to take this one anyways since the syllabus's a little bit different_

**Comment by ericdouglas** [comment]
@gillchristian yes, for sure :smile: 

For your public profile, though, it's better to create some project to show what you learned in those classes. Of course, it's just a suggestion.

**Comment by gillchristian** [comment]
Yup, thought about that same thing.

Thanks for the quick answer!

**Comment by lixsee** [comment]
What sort of project could you create for Calculus, Algebra, and Discrete Math to prove your proficiency in them?

**Comment by andrecsq** [comment]
My discrete math course in college finishes in the 6th lecture of MIT 24-lecture course (I would skip 18 lectures if I didn't take it "again"). Pay attention because you could be missing a lot of stuff.
