### ISSUE TITLE
Algorithms Part 2 bad link

### ISSUE THREAD

**Issue by andrewrod33** [open-source-society/computer-science#384]
On https://ossu.firebaseapp.com/#/curriculum there is a bad link for Algorithms Part 2. It's currently pointed to https://www.coursera.org/course/algs4partII. Looks like the URL should be https://www.coursera.org/learn/algorithms-part2.

**Comment by ericdouglas** [comment]
@andrewrod33 you should use [this method](https://github.com/open-source-society/computer-science#how-to-track-and-show-your-progress) to track your progress.

The web app isn't receiving updates.

**Comment by andrewrod33** [comment]
Thanks for the information!
