### ISSUE TITLE
Operating Systems and System Programming course to be removed

### ISSUE THREAD

**Issue by trevorhalvorson** [open-source-society/computer-science#392]
UC Berkeley released a statement stating they will be removing legacy course content on March 15th, 2017: http://news.berkeley.edu/2017/02/24/faq-on-legacy-public-course-capture-content/

If you visit the [Operating Systems and System Programming](https://www.youtube.com/view_play_list?p=-XXv-cvA_iBDyz-ba4yDskqMDY6A1w_c) YouTube playlist you can see the banner image at the top confirming that they will be removing the content.

Is there a plan for re-hosting this course or finding an alternative?

**Comment by srs1978** [comment]
Just a bit of an FYI, but the DOJ has been writing letters to universities for making sure their online content is ADA complaint, specifically deaf people have been trying to get the DOJ to sue all the schools for making free content and not making it accessible.  How it's being handled at the moment is "meh".

**Comment by crmackay** [comment]
I believe @hanjiexi 's branch/proposal removes this course, and replaces it with Nand to Tetris and then reading from a U of wisconsin course (http://pages.cs.wisc.edu/~remzi/OSTEP/)

**Comment by ericdouglas** [comment]
@trevorhalvorson thanks for pointing this out, we'll fix it in our next curriculum update.

**Comment by sdsahib** [comment]
Hello guys, But the link is still available. We can ask for their permission and can share those youtube videos  with the community  account on youtube.

**Comment by carsnwd** [comment]
Here is an alternative OS course from [Georgia Tech on Udacity.](https://www.udacity.com/course/introduction-to-operating-systems--ud923?utm_medium=referral&utm_campaign=api)

**Comment by ericdouglas** [comment]
Closed due to v7 release
