### ISSUE TITLE
How to Code: Systematic Programming Design Links Don't Work

### ISSUE THREAD

**Issue by bravech** [open-source-society/computer-science#394]
The links for How to Code: Systematic Programming Design 1, 2, and 3 don't seem to be working and instead redirect to the MicroMasters Program for Software Development. The classes themselves seem to be still working since I enrolled in all 3 just to save them, and I can still access them. Also, if you search for the course on EdX, it doesn't show in search results.

**Comment by ericdouglas** [comment]
@bravech thank you for pointing this out, it'll be fixed in our next curriculum update.

**Comment by li-xinyang** [comment]
@ericdouglas Is there a estimated date for releasing next curriculum update?

**Comment by ericdouglas** [comment]
@li-xinyang I'm actively working on it right now and I'll use all my available time to finish it ASAP so I hope to finish it in 1 ~ 2 weeks.

**Comment by aykutyaman** [comment]
@ericdouglas looking forward to the new version of Curriculum

**Comment by wxt2005** [comment]
Before new curriculum comes out, you can use these link to directly enroll these 3 courses

[How to Code: Systematic Program Design - Part 1](https://courses.edx.org/register?utm_campaign=gotocourse&utm_source=CourseTalk&email_opt_in=false&utm_medium=coursepage&course_id=course-v1%3AUBCx+SPD1x+2T2016&enrollment_action=enroll)

[How to Code: Systematic Program Design - Part 2](https://courses.edx.org/register?utm_campaign=gotocourse&utm_source=CourseTalk&email_opt_in=false&utm_medium=coursepage&course_id=course-v1%3AUBCx+SPD2x+2T2016&enrollment_action=enroll)

[How to Code: Systematic Program Design - Part 3](https://courses.edx.org/register?utm_campaign=gotocourse&utm_source=CourseTalk&email_opt_in=false&utm_medium=coursepage&course_id=course-v1%3AUBCx+SPD3x+2T2016&enrollment_action=enroll)

**Comment by ericdouglas** [comment]
Closed due to v7 release
