### ISSUE TITLE
I can't find the git courses and project suggestions in this new curriculum.

### ISSUE THREAD

**Issue by real-gobs** [open-source-society/computer-science#397]
Have you guys removed the git/github tutorials and project suggestions from the old curriculum? I think they were very necessary to be in the curriculum.

**Comment by ericdouglas** [comment]
@real-gobs thanks for pointing this out. You can see those previous links [here](https://github.com/open-source-society/computer-science/blob/8a52c2ad6e5f45cd831811b5e100b8bd4e1f7977/README.md#project-suggestions).
