### ISSUE TITLE
Calculus 2 Recommendation Does not cover all of Calc 2 material

### ISSUE THREAD

**Issue by waciumawanjohi** [open-source-society/computer-science#399]
The recommendation for Calculus 2 is:
https://www.coursera.org/learn/advanced-calculus

However, this course skips a good deal of material generally taught in Calculus 2, including Parametric curves and polar coordinates. Students will need both if they continue on to Multivariable Calculus in Advanced Math (which itself is a pre-req for Probability).

I would recommend replacing the current Calc 2 course with:
MITx: 18.01.3x Calculus 1C: Coordinate systems and infinite series
https://www.edx.org/course/calculus-1c-coordinate-systems-infinite-mitx-18-01-3x-0

**Comment by hanjiexi** [comment]
This is tricky. You are right that [Ohio State's Calculus Two on Coursera](https://www.coursera.org/learn/advanced-calculus) doesn't teach those topics, and that MIT 18.01 Single-variable Calculus (available on edX as [1A](https://www.edx.org/course/calculus-1a-differentiation-mitx-18-01-1x-0), [1B](https://www.edx.org/course/calculus-1b-integration-mitx-18-01-2x-0), and [1C](https://www.edx.org/course/calculus-1c-coordinate-systems-infinite-mitx-18-01-3x-0)) is a prerequisite for [MIT 18.02 Multivariable Calculus](https://ocw.mit.edu/courses/mathematics/18-02sc-multivariable-calculus-fall-2010/index.htm).

More importantly, it is also a prerequisite for [MIT 6.042 Mathematics for Computer Science](https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-042j-mathematics-for-computer-science-spring-2015/syllabus/) under Core CS. So it is critical that we figure this out and get it right.

The goal of the calculus courses in Core CS is to prepare the student for MIT Math for CS, which itself prepares the student for studying algorithms. **So the key question, as far as Core CS is concerned, is whether the topics of `parametric equations` and `polar coordinate systems` is necessary for MIT Math for CS.**

I can't solve this right now, but here are some things to note:
* MIT Multivariable Calculus [covers parametric curves](https://ocw.mit.edu/courses/mathematics/18-02sc-multivariable-calculus-fall-2010/1.-vectors-and-matrices/part-c-parametric-equations-for-curves/).
* Based on my experience taking Ohio State Calculus One, some familiarity with polar coordinate systems seems to be *assumed* of the student (i.e. as if the student had studied it previously).
* Counter-intuitively, Khan Academy categorizes [parametric equations as an Algebra > Trigonometry topic](https://www.khanacademy.org/math/algebra-home/alg-trig-functions/alg-parametric/v/parametric-equations-1) (i.e. pre-calculus) and [polar coordinates as a multivariable calculus topic](https://www.khanacademy.org/math/multivariable-calculus/integrating-multivariable-functions/double-integrals-a/v/polar-coordinates-1).
  * However, it does include [Area enclosed by a polar formula](https://www.khanacademy.org/math/calculus-home/integration-applications-calc/area-defined-by-polar-graphs-calc/v/formula-area-polar-graph) as a calculus one topic under integration applications.

I'll continue to look into this. If anyone has any helpful information to add, please do!

**Comment by waciumawanjohi** [comment]
The syllabus page for MIT 6.042 (which you linked) lists the calculus topics necessary and does not mention parametric curves or polar coordinates:

> Prerequisite
> The prerequisite is 18.01 Single Variable Calculus. In particular, some familiarity with sequences and series, limits, and differentiation and integration of functions of one variable are necessary.

I would need to take a closer look at the 2015 version of 6.042 to have a more fine grained view of what is covered.

On Khan Academy:
While Khan Academy covers the existence of parametric curves, those lectures do not cover derivatives of parametric curves.

MIT 18.01 explicitly says that its content on [parametric curves and polar coordinates are preparation for multivariable calculus](https://youtu.be/TpWQlKHPyJ4?t=41m0s). Also that [the polar coordinate content introduced in 18.01 will be needed a lot in 18.02](https://youtu.be/XRkgBWbWvg4?t=45m10s).

At the very least, 18.01 C should be placed in Advanced Math before 18.02.

**Comment by hanjiexi** [comment]
Thank you. This is very helpful! Eric and I think it will be best to leave Core Math untouched for now since we prefer to have more concise math courses — Ohio State Calculus is 23 weeks, MIT Calculus is 36 weeks — as this is a CS curriculum not a pure math one. Therefore, I tentatively agree with you that it is necessary to put MIT 18.01 part C right before Multivariable Calculus under Advanced Math.

This would mean that we would need to add a note that "you have already studied some of this material in Core Math". I'm fine with this, but perhaps another option would be to find the relevant lectures [from YouTube](https://www.youtube.com/watch?v=7K1sB05pE0A&list=PL590CCC2BC5AF3BC1) and create a custom playlist of only the videos needed for learning that material, or, similarly, finding some other resource that teaches the exact same content.

**Comment by ericdouglas** [comment]
@hanjiexi I liked both solutions but add MIT 18.01 part C before Multivariable Calculus sounds better to me. Students can skip the content they know or use it to review/refresh the topic.

**Comment by waciumawanjohi** [comment]
Perhaps the best solution is to link to MIT Open Courseware Scholar version of 18.01. By doing so, students can be directed [right to the work on parametric curves and polar coordinates](https://ocw.mit.edu/courses/mathematics/18-01sc-single-variable-calculus-fall-2010/unit-4-techniques-of-integration/part-c-parametric-equations-and-polar-coordinates/), while still seeing all of the other material available.

This may also be best because it looks like edX has put the next session of 18.01 in the hopper and now when students sign up, instead of getting the archived versions that can be worked immediately, they are signed up for [courses that won't open until later this summer/later next spring](https://www.edx.org/course?search_query=calculus+1a).

In terms of finding other resources that teach the same material, on the edX platform there are two different calculus courses from DavidsonNext which include parametric curves ([Example A](https://www.edx.org/course/apr-calculus-bc-davidson-next-calapbcx)) ([Example B](https://www.edx.org/course/apr-calculus-challenging-concepts-davidson-next-calapccx-0)). Coursera has a calculus course from UPenn that is split into [5 mini courses](https://www.coursera.org/courses?languages=en&query=calculus+pennsylvania), but it's not clear that any of them cover the material in question.
