### ISSUE TITLE
Mathematics For Computer Science Solutions

### ISSUE THREAD

**Issue by btke** [open-source-society/computer-science#405]
Does anyone can share solutions for this course?
I think it's really important doing practices.

**Comment by li-xinyang** [comment]
I do not think it is a good place for asking this question. According to most of MOOC Code of Conduct, the learner should not share the solution on the Internet. (Below is quote from Coursera Honor Code)

> You may not share your solutions to homework, quizzes, or exams with anyone else unless explicitly permitted by the instructor. This includes anything written by you, as well as any official solutions provided by the course staff.

However, I think if you have any question you can post it at 

- https://www.reddit.com/r/programming/
- https://math.stackexchange.com/

I believe you can get plenty of help there. Good luck.

**Comment by btke** [comment]
the question is that there is no feedback for all the problems

**Comment by li-xinyang** [comment]
I do understand that issue. You may want to search online or getting help from the related online forum.

What I want to say is, this is not a good place to ask this question because it is not related to this project ("open-source-society/computer-science").

**Comment by btke** [comment]
i think it is connected so that people who attend this project can have a better understanding to achieve their goals.

**Comment by ericdouglas** [comment]
@btke we have a subreddit and a chat room for this kind of question. Feel free to ask there:

[Subreddit](https://www.reddit.com/r/opensourcesociety/)
[Gitter](https://gitter.im/open-source-society/computer-science)
