### ISSUE TITLE
Duplicate of MIT 6.00.1x (Python course) in extras

### ISSUE THREAD

**Issue by Implaier** [open-source-society/computer-science#406]
"Introduction to Computer Science and Programming Using Python" course is mentioned in both main curriculum and extras section, which seems redundant.

[Main](https://github.com/open-source-society/computer-science#introduction-to-computer-science)
[Extras](https://github.com/open-source-society/computer-science/blob/master/extras/courses.md#programming)

**Comment by ericdouglas** [comment]
@Implaier many thanks, fixed :+1:

**Comment by xxzozaxx** [comment]
@ericdouglas I want to mension that, _"Introduction to Computer Science and Programming Using Python"_ course has 2 parts.
in main curriculum there are part 1.
I just wondering what about part 2

**Comment by raphiw** [comment]
Part 2 of that series is a great course (just finished taking it), but it's very data science focused with little new programming taught. It's included in the data science curriculum, but I think it makes sense keeping it out of the main cs curriculum.

**Comment by xxzozaxx** [comment]
So I can/should skip it (Now, I taking part 1)
