### ISSUE TITLE
Functional Concepts

### ISSUE THREAD

**Issue by TYRONEMICHAEL** [open-source-society/computer-science#411]
Are there any courses in the curriculum that cover Functors, Applicatives, Monads, Monoids and SemiGroups?

This is the only [course](https://www.coursera.org/specializations/scala) that seems to cover some of the concepts. I am just not sure in how much detail.

**Comment by hanjiexi** [comment]
Hi,

The course requires reading Learn You a Haskell for Great Good:
http://learnyouahaskell.com/functors-applicative-functors-and-monoids

That isn't the *best* resource for learning functional concepts, but it
seems to be one of the best free resources. The best resource is Haskell
Programming from First Principles: http://haskellbook.com but it costs
money so we can't put it on the main curriculum.

**Comment by TYRONEMICHAEL** [comment]
That is unfortunate. It really seems to be one of the best resources to learn functional concepts. I know this has been discussed in length, but if there really is a better paid option, I believe we should at least let learners know.

**Comment by TYRONEMICHAEL** [comment]
Also I am not sure if this has been discussed, but since we are on the topic, it seems you have to pay a monthly fee of $49 in order to enroll for the algorithms course.

**Comment by li-xinyang** [comment]
@TYRONEMICHAEL SEE THE FINE PRINT AT THE BOTTOM 😱😱😱😱😱😱😱😱😱

> Audit this course

**Comment by TYRONEMICHAEL** [comment]
Awesome. Thank you.

**Comment by ericdouglas** [comment]
@TYRONEMICHAEL @hanjiexi we can put a note saying that a paid resource is better than a free one.

What we shouldn't do is to put **only** a paid resource with no **free** alternative.

E.g.

- **Required** to learn about monads, laziness, purity: Learn You a Haskell for a Great Good!
  -  **OBS**: best resource to learn Haskell: [Haskell Programming from First Principles](http://haskellbook.com/) `paid`

what do you think?

**Comment by hanjiexi** [comment]
I agree on all fronts, I will try to get some fixes out this week!

**Comment by TYRONEMICHAEL** [comment]
I came across the following resource on [category theory](https://bartoszmilewski.com/2014/10/28/category-theory-for-programmers-the-preface/). I have only just started reading the material, but could be another alternative to learn functional concepts as a free resource.

**Comment by illucent** [comment]
http://www.logicmatters.net (Category Theory for Philosophers): theory
