### ISSUE TITLE
Is Trello board up-to-date with current advised curriculum?

### ISSUE THREAD

**Issue by KathrynN** [open-source-society/computer-science#412]
The Trello board is actively encouraged in the READ.ME as a place for people to copy from and monitor their progress.  I am not sure if this has been updated to match the current state of the course, which undergoes several changes every quarter.

This issue is for someone (probably me) to go through and ensure that the Trello board is up-to-date with the course curriculum.

Not covered by the scope:
* Should people be informed when there is a new version of the Trello board
* Will this affect people's copies (assume not, Trello to answer)

**Comment by KathrynN** [comment]
After further inspection, it appears that the Trello board is up-to-date.

**Comment by ericdouglas** [comment]
Yes, the Trello board is up to date with our curriculum v7 :+1:
