### ISSUE TITLE
Minor option?

### ISSUE THREAD

**Issue by aGilvarry** [open-source-society/computer-science#413]
Hi! I was wondering, has  adding a "minor" option to the curriculum ever been considered? I ask because my end goal isn't to be a "standard" software developer, or whatever, but rather to complement the GIS work I do at my job/Masters program. I began a Minor in Computer Science at University a few years ago but had to graduate before I finished. At the moment I at least plan on finishing the Core curriculum, but it could be nice to have some evaluation that would be equivalent to what you'd get in a standard CS minor, if that doesn't deviate too far from the mission of this curriculum.

Thanks for listening!

**Comment by hanjiexi** [comment]
My design of Core CS was based roughly on the core requirements universities often give to CS majors, while Advanced CS is analogous to the electives that majors would be required to choose from. I haven't looked too much at requirements for CS minors, but I would guess Core CS is comparable to a really, really heavy CS minor.

What really makes the difference is Core Applications: in the effort to create well-rounded *generalists*, the Core curriculum includes graphics, cryptography, and machine learning, but these are hardcore topics that a CS minor might not need. For a CS minor, often their "applied CS" is equivalent to their main area of study -- bioinformatics, data science, etc.

So, my casual suggestion is to do most of Core CS, but dropping any of those three "Core applications" courses that you don't need for your specialty. As far as evaluation goes, the [last course in Core applications](https://www.edx.org/course/software-development-capstone-project-ubcx-softengprjx#!) -- which I do suggest doing -- is a large software development project that includes some automated testing feedback. You can also elicit feedback from the OSSU community on it (assuming they permit you to share your code; you might have to get permission).

I hope that helps. In the future I think OSSU will have other tech-related curriculums, which might require us to modularize the CS curriculum even more to make it easier to integrate parts of it with the other curriculums, but that's probably a long way off.

**Comment by aGilvarry** [comment]
thanks for the advice!
