### ISSUE TITLE
Prerequisites for core programming readings?

### ISSUE THREAD

**Issue by aGilvarry** [open-source-society/computer-science#416]
What are the Prerequisites for the haskell and prolog books under core programming? At what point I should have enough under my belt to tackle those?

**Comment by hanjiexi** [comment]
Within the context of the course, they intended as a sequel to [Coursera Programming Languages](https://www.coursera.org/learn/programming-languages), but actually you can start either of them whenever you want really. They don't assume prior knowledge. (Actually, the less you already know about imperative and object-oriented programming, the easier Haskell is to learn!)
