### ISSUE TITLE
Learning how to learn and MIT Challenge

### ISSUE THREAD

**Issue by rip222** [open-source-society/computer-science#417]
Hi there. Just joined the university and started to take the first course.

I just wanted to know one thing. I 've seen previously that you had a section in the contents or somewhere else which contained a link to the course named "Learning how to learn" and MIT Challenge.. Where are they and/or why have you removed them from the page?

**Comment by ericdouglas** [comment]
@rip222 you can see those links [here](https://github.com/open-source-society/computer-science/tree/9ed8c312053af14d82c5988490bb85dff4fcdb36#motivation--preparation).

**Comment by hanjiexi** [comment]
Those are good resources but we just wanted to make the main CS curriculum page more concise and focused on CS only. Maybe we could add them to the [FAQ](https://github.com/open-source-society/computer-science/blob/master/FAQ.md).

**Comment by rip222** [comment]
thank you guys!
