### ISSUE TITLE
Educational Facebook page

### ISSUE THREAD

**Issue by ramirio** [open-source-society/computer-science#72]
It would be nice a educational Facebook page of the project, so we can add them to the education section of our profile (and let our friends know that this project exist).

**Comment by ericdouglas** [comment]
This is a great suggestion, @ramirio ! I'll create one for us ASAP :smile:

**Comment by ericdouglas** [comment]
@ramirio [here](https://www.facebook.com/ossuniversity) it is! :wink:

**Comment by ramirio** [comment]
:tada:
