### ISSUE TITLE
Internships and participation to real-world projects

### ISSUE THREAD

**Issue by heri** [open-source-society/computer-science#79]
The courses listed are a very good start. 

However, the best universities such as University of Waterloo encourage students to do internships or participate in external projects early on.

Real-world projects lets you understand how to apply your theoritical skills to the needs of the people 

As such, I would add:
* recommend students to go to local hackathons. Those are good to learn how to work with teams, how their skills are compared to other programmers, and build self-worth
* recommend students to search for 2 or 3 months internships in local startups. Often technology startups don't mind if people do not have a university degree. So having a few coursera courses could be enough
* recommend students to do simple sites or apps for local small businesses. These would be limited in time (less than 2 weeks of work) and would help understand the value of code

**Comment by ericdouglas** [comment]
@heri you're right! We have some of those tips [here](https://github.com/open-source-society/computer-science-and-engineering#be-creative).

**Comment by marrujoalex** [comment]
While I think local hackathons are highly productive and valuable in not only working with teams and networking, I think that also depends on your geographical area in where you reside.

Where I live (a desert area in southern california), there aren't many small businesses that are willing to get a website or application.

Would you have any suggestions for these kind of situations? I've thought of just adding more projects to our respective GitHub accounts and hopefully sharing them to increase exposure, but I think in these situations, there is more effort needed here.

**Comment by ericdouglas** [comment]
@marrujoalex [here](https://github.com/open-source-society/computer-science#be-creative) we have some tips... Fell free to add more tips :smile:
