### ISSUE TITLE
I'm missing some hardware courses

### ISSUE THREAD

**Issue by bestknighter** [open-source-society/computer-science#85]
Hello everyone!

As some may have noticed, this repository's title says Computer Science and Engineering. So, I expected some hardware courses too! This covers CS courses and just the software part of CE. Is there any hardware related MOOC courses out there? Would be awesome if we had microprocessors, microcontrollers, arduino/raspberry pi programming, embedded systems, electronics, assembly programming principles, etc. I know that most of these stuff should be learned together with laboratory classes but, knowing the theoretical part is already a huge plus. And if you can afford to buy some of these stuff (in some countries they are not that expensive), you'll have the practical skills too!

I'm not complaining at all! This is an **AWESOME** project and I want to congratulate whoever had this idea. But wouldn't be awesome if we had those courses added?

**Comment by graveto** [comment]
Both Coursera and EdX have hardware oriented courses. Also some Internet of Things courses.

**Comment by ericdouglas** [comment]
@bestknighter you're totally right, we need to add some topics/courses here.

I think that we need to change the title of this repository to be just **computer-science**, and make some specific lists to another topics.

If we put **a lot** of courses here it can demotivate people. So I think that is better to keep this curriculum as lean as possible, and after we can create curriculums for some specializations.

What do you think about it?

**Comment by ericdouglas** [comment]
@graveto the IoT course are not free :disappointed:

**Comment by bestknighter** [comment]
@ericdouglas Indeed! Making another list is a good idea! But, what courses it would have? Probably programming wouldn't be so big of a focus in that one, right?

**Comment by ericdouglas** [comment]
@bestknighter right. We can have lists related to Electrical Engineering  courses, Math, more topics about CS, etc.

**Comment by bestknighter** [comment]
@ericdouglas Ok! As soon as you create the Computer Engineering course repository in the Open Source Society org, I'll fork it and start contributing!
But before creating that, I saw [this other issue](https://github.com/open-source-society/computer-science/issues/93) and I think that this other repository should be created after the curriculum for this one is finished. In this way, for the initial commit, you can just copy-paste it, remove those courses that aren't needed for a CE course and change some of the text to fit the new content.
What do you think?

**Comment by ericdouglas** [comment]
@bestknighter awesome! We can do it, for sure. Let's finish our CS curriculum first (what I'll do today), and wait a little to enhance our structure (we're growing fast), and then we can think in start new curriculums.

Thanks for your interest!

:smile:
