### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by gpineda14** [open-source-society/computer-science#87]
- **Name**: Guillermo Pineda
- **GitHub**: [@gpineda14]()
- **Twitter**: []()
- **Linkedin**: []()
- **Website**: []()

## Completed Courses

**Name of the Section**

Course|Files
:--|:--:| []()

**Comment by jbhum** [comment]
Please open issue [#145](https://github.com/open-source-society/computer-science/issues/145) and place your enrollment at the end of that file.

**Comment by ericdouglas** [comment]
@jbhum ty :smile:
