### ISSUE TITLE
Linux? 

### ISSUE THREAD

**Issue by brandonskerritt51** [open-source-society/computer-science#88]
Can we have a course for basic Linux use, like introduction to the command line from Code academy? I believe Linux is used heavily in the industry and having a quick 3 hour code academy course on it couldn't hurt?

**Comment by maicoqb** [comment]
+1 :+1:
I think is very important know how to work with Linux. :smile:

**Comment by ericdouglas** [comment]
I think that we can advise that a UNIX system is more suitable for programming, but add an "obligatory" course into the curriculum about it seems a little strange to me.

Do you know some university that have such course in its curriculum?

**Comment by waterlooSunset** [comment]
CS50 has a gentle introduction to Ubuntu with the CS50 appliance they ask you to use for the class. It goes into some basics. I think becoming familiar with *nix is implicit to completing the OSS curriculum. You'll have to learn it along the way to complete some of the courses.

**Comment by Ebisu77** [comment]
There are two courses about operating system in curricullum already, quote from first ones sylabus: "Lectures are based on a study of UNIX and research papers." I don't think we need to add other course specifically about linux. Two courses already covering topic of operating systems are in my opinion sufficient.

**Comment by ericdouglas** [comment]
@waterlooSunset @Ebisu77 :+1:

**Comment by mseyne** [comment]
I plan to take this one :
https://www.edx.org/course/introduction-linux-linuxfoundationx-lfs101x-2
