### ISSUE TITLE
More Math

### ISSUE THREAD

**Issue by AustinMatherne** [open-source-society/computer-science#93]
The curriculum could use more math. Ben Nash posted a similar list last year which included a pretty solid foundation for math.

http://spin.atomicobject.com/2015/05/15/obtaining-thorough-cs-background-online/

**Comment by ericdouglas** [comment]
@AustinMatherne many thanks for that **awesome** link!

We need more courses about **Math**, **Computer Architecture**, **Theory of CS** and maybe Physics.

Until the end of this week I hope that we have our curriculum finished.

Thanks again for pointing that out! :smile:

**Comment by ericdouglas** [comment]
I'm also thinking in split the Math course by its subtopics, in that way we don't need to do all of them at once.

We shouldn't do more than two courses sequentially about this topic.

What you think about it @AustinMatherne ?

**Comment by AustinMatherne** [comment]
Yeah, splitting the math up is a good idea. It would also probably be smart to include a short blurb about what makes each subtopic applicable for the folks without much of a math background.
