### ISSUE TITLE
Netsec and Appsec Courses

### ISSUE THREAD

**Issue by Nolski** [open-source-society/computer-science#95]
I'm sure there have to be at least a few great courses in intro to netsec and appsec that would be invaluable for those looking to get into development.

**Comment by ericdouglas** [comment]
Hey, @Nolski !

Do you have some courses in mind?

**Comment by waterlooSunset** [comment]
Hi @Nolski & @ericdouglas I found this one maybe it's along the lines of what you are looking for...

https://www.futurelearn.com/courses/introduction-to-cyber-security

**Comment by Nolski** [comment]
@ericdouglas This is a bit more of a tutorial but I feel like the Intro to Metasploit also provides a good foundation in netsec. https://www.offensive-security.com/metasploit-unleashed/introduction/ Although I'm not super advanced in this field so I'm sure someone else may have a better idea of what to put.

**Comment by ericdouglas** [comment]
Closing this issue. @waterlooSunset thanks for that suggestion, I'll add this course to our curriculum. :smile:
