### ISSUE TITLE
Advanced system courses 404

### ISSUE THREAD

**Issue by j1nxie** [open-source-society/computer-science#952]
As stated in the title, as of submitting this issue, the links to the three Advanced system courses:

[https://www.edx.org/course/computation-structures-part-1-digital-circuits](https://www.edx.org/course/computation-structures-part-1-digital-circuits)  
[https://www.edx.org/course/computation-structures-2-computer-architecture-2](https://www.edx.org/course/computation-structures-2-computer-architecture-2)  
[https://www.edx.org/course/computation-structures-3-computer-organization-2](https://www.edx.org/course/computation-structures-3-computer-organization-2)

all return to a 404 on edX.

**Comment by py4edotcom** [comment]
![advsys](https://user-images.githubusercontent.com/92250810/136690464-c13c3971-6f5c-4def-a9ac-d76b4114e139.png)
![oll](https://user-images.githubusercontent.com/92250810/136690519-11fae575-bb3f-4e3f-8b2f-aa517526ae98.png)
