### ISSUE TITLE
Derek

### ISSUE THREAD

**Issue by seashaw1234** [open-source-society/computer-science#98]
- **Name**: Derek Davis
- **GitHub**: [@seashaw1234]()
- **Twitter**: [@onceathought]()
- **Linkedin**: [link]()
- **Website**: [yourblog.com]()

## Completed Courses

**Name of the Section**

Course|Files
:--|:--:
Course Name| [link]()

**Comment by sarath49** [comment]
Hi, Please close it and open it in issue #31 as comment for now
Thanks :)
